#!/usr/bin/env node

/** Generate the exhaustive default-deny RLS migration from the schema inventory. */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const inventory = JSON.parse(await readFile(path.join(root, "docs/migration/inventory.json"), "utf8"));
const tenantTables = inventory.tables.filter((table) => table.columns.some((column) => column.name === "organization_id"));
const propertyScoped = new Set(tenantTables.filter((table) => table.columns.some((column) => column.name === "property_id")).map((table) => table.name));
propertyScoped.delete("access_grants");

const ident = (value) => `"${value.replaceAll('"', '""')}"`;
const policy = (table, action, suffix, using, check = using) => [
  "",
  `DROP POLICY IF EXISTS ${ident(`${table}_${suffix}`)} ON public.${ident(table)};`,
  `CREATE POLICY ${ident(`${table}_${suffix}`)} ON public.${ident(table)}`,
  `  FOR ${action} TO aval_app`,
  action === "INSERT" ? null : `  USING (${using})`,
  action === "SELECT" || action === "DELETE" ? null : `  WITH CHECK (${check})`,
].filter((line) => line !== null).join("\n") + ";";

const blocks = [`-- GENERATED by scripts/migration/generate-rls.mjs.
-- Request identity is supplied with transaction-local set_config calls.

CREATE SCHEMA IF NOT EXISTS aval_private;
REVOKE ALL ON SCHEMA aval_private FROM PUBLIC;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aval_app') THEN
    CREATE ROLE aval_app NOLOGIN NOINHERIT NOBYPASSRLS;
  END IF;
END $$;
GRANT aval_app TO postgres;
GRANT USAGE ON SCHEMA public TO aval_app;

CREATE OR REPLACE FUNCTION aval_private.current_principal_id() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('aval.principal_id', true), '')
$$;

CREATE OR REPLACE FUNCTION aval_private.current_organization_id() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('aval.organization_id', true), '')
$$;

CREATE OR REPLACE FUNCTION aval_private.has_org_access(target_org text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id()
    AND EXISTS (
      SELECT 1 FROM public.access_grants grant_row
      JOIN public.principals principal ON principal.id = grant_row.principal_id AND principal.status = 'active'
      WHERE grant_row.organization_id = target_org
        AND grant_row.principal_id = aval_private.current_principal_id()
        AND grant_row.revoked_at IS NULL
        AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
    )
$$;

CREATE OR REPLACE FUNCTION aval_private.has_org_role(target_org text, allowed_roles text[]) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id()
    AND EXISTS (
      SELECT 1 FROM public.access_grants grant_row
      JOIN public.principals principal ON principal.id = grant_row.principal_id AND principal.status = 'active'
      WHERE grant_row.organization_id = target_org
        AND grant_row.principal_id = aval_private.current_principal_id()
        AND grant_row.role = ANY(allowed_roles)
        AND grant_row.organization_scope
        AND grant_row.revoked_at IS NULL
        AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
    )
$$;

CREATE OR REPLACE FUNCTION aval_private.can_access_property(target_org text, target_property text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id() AND EXISTS (
    SELECT 1 FROM public.properties property_row
    JOIN public.access_grants grant_row ON grant_row.organization_id = property_row.organization_id
      AND grant_row.principal_id = aval_private.current_principal_id()
      AND grant_row.revoked_at IS NULL
      AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
      AND (
        grant_row.organization_scope
        OR grant_row.property_id = property_row.id
        OR grant_row.ownership_entity_id = property_row.ownership_entity_id
        OR grant_row.portfolio_id = property_row.portfolio_id
        OR grant_row.region_id = property_row.region_id
      )
    WHERE property_row.organization_id = target_org AND property_row.id = target_property
  )
$$;

CREATE OR REPLACE FUNCTION aval_private.can_manage_property(target_org text, target_property text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id() AND EXISTS (
    SELECT 1 FROM public.properties property_row
    JOIN public.access_grants grant_row ON grant_row.organization_id = property_row.organization_id
      AND grant_row.principal_id = aval_private.current_principal_id()
      AND grant_row.role = ANY(ARRAY['org_admin','regional_manager','property_manager','operator'])
      AND grant_row.revoked_at IS NULL
      AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
      AND (
        grant_row.organization_scope
        OR grant_row.property_id = property_row.id
        OR grant_row.ownership_entity_id = property_row.ownership_entity_id
        OR grant_row.portfolio_id = property_row.portfolio_id
        OR grant_row.region_id = property_row.region_id
      )
    WHERE property_row.organization_id = target_org AND property_row.id = target_property
  )
$$;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO aval_app;
`];

for (const table of tenantTables) {
  const name = table.name;
  blocks.push(`\nALTER TABLE public.${ident(name)} ENABLE ROW LEVEL SECURITY;\nALTER TABLE public.${ident(name)} FORCE ROW LEVEL SECURITY;`);
  if (name === "access_grants" || name === "approval_authorities" || name === "sso_connections") {
    const admin = `aval_private.has_org_role(organization_id, ARRAY['org_admin'])`;
    blocks.push(policy(name, "SELECT", "select", admin), policy(name, "INSERT", "insert", admin), policy(name, "UPDATE", "update", admin), policy(name, "DELETE", "delete", admin));
  } else if (name === "properties") {
    blocks.push(
      policy(name, "SELECT", "select", "aval_private.can_access_property(organization_id, id)"),
      policy(name, "INSERT", "insert", "aval_private.has_org_role(organization_id, ARRAY['org_admin'])"),
      policy(name, "UPDATE", "update", "aval_private.can_manage_property(organization_id, id)"),
      policy(name, "DELETE", "delete", "aval_private.can_manage_property(organization_id, id)"),
    );
  } else if (propertyScoped.has(name)) {
    const read = "(property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id)";
    const write = "(property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id)";
    blocks.push(policy(name, "SELECT", "select", read), policy(name, "INSERT", "insert", write), policy(name, "UPDATE", "update", write), policy(name, "DELETE", "delete", write));
  } else {
    const read = "aval_private.has_org_access(organization_id)";
    const write = "aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])";
    blocks.push(policy(name, "SELECT", "select", read), policy(name, "INSERT", "insert", write), policy(name, "UPDATE", "update", write), policy(name, "DELETE", "delete", write));
  }
}

blocks.push(`
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations FORCE ROW LEVEL SECURITY;
${policy("organizations", "SELECT", "select", "aval_private.has_org_access(id)")}
${policy("organizations", "UPDATE", "update", "aval_private.has_org_role(id, ARRAY['org_admin'])")}

ALTER TABLE public.principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.principals FORCE ROW LEVEL SECURITY;
${policy("principals", "SELECT", "select", "id = aval_private.current_principal_id()")}

ALTER TABLE public.identity_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.identity_links FORCE ROW LEVEL SECURITY;
${policy("identity_links", "SELECT", "select", "principal_id = aval_private.current_principal_id()")}

CREATE OR REPLACE FUNCTION aval_private.protect_final_org_admin() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE target_org text := COALESCE(OLD.organization_id, NEW.organization_id);
BEGIN
  IF OLD.role = 'org_admin' AND OLD.organization_scope AND OLD.revoked_at IS NULL
     AND (TG_OP = 'DELETE' OR NEW.role <> 'org_admin' OR NOT NEW.organization_scope OR NEW.revoked_at IS NOT NULL) THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.access_grants candidate
      WHERE candidate.organization_id = target_org
        AND candidate.id <> OLD.id
        AND candidate.role = 'org_admin'
        AND candidate.organization_scope
        AND candidate.revoked_at IS NULL
        AND (candidate.expires_at IS NULL OR candidate.expires_at > statement_timestamp())
    ) THEN RAISE EXCEPTION 'cannot remove the final organization administrator' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$;

DROP TRIGGER IF EXISTS access_grants_final_admin_guard ON public.access_grants;
CREATE CONSTRAINT TRIGGER access_grants_final_admin_guard
AFTER UPDATE OR DELETE ON public.access_grants DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION aval_private.protect_final_org_admin();

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA aval_private FROM PUBLIC;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA aval_private TO aval_app;
`);

const output = path.join(root, "supabase/migrations/20260910000200_default_deny_rls.sql");
await writeFile(output, blocks.join("\n").replaceAll("\r\n", "\n"));
console.log(JSON.stringify({ tenantTables: tenantTables.length, propertyScoped: propertyScoped.size, output: path.relative(root, output) }));
