// GENERATED by scripts/migration/generate-postgres-schema.mjs.
// Edit db/schema.ts or the generator, then run npm run db:postgres:schema.

import { sql } from "drizzle-orm";
import { bigint, boolean, check, doublePrecision, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const userOnboarding = pgTable("user_onboarding", {
  userId: text("user_id").notNull(),
  organizationId: text("organization_id").notNull(),
  preferences: text("preferences").notNull(),
  step: integer("step").notNull().default(0),
  completed: boolean("completed").notNull().default(false),
  introSeen: boolean("intro_seen").notNull().default(false),
  revision: integer("revision").notNull().default(1),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [uniqueIndex("user_onboarding_user_org_uq").on(table.userId, table.organizationId)]);

// Supports both password accounts and platform identities, which need not
// have a row in users. The API always derives user_id from the session.
export const userAppearance = pgTable("user_appearance", {
  userId: text("user_id").primaryKey(),
  preferences: text("preferences").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
});

// Real customer accounts for deployments outside ChatGPT Sites, where there
// is no platform-injected identity header — email/password, hashed with
// PBKDF2 (lib/auth/password.ts), never stored or logged in plain text.
export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    displayName: text("display_name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [uniqueIndex("users_email_uq").on(table.email)],
);

// Stable application identities. Supabase, ChatGPT, and future enterprise SSO
// subjects link here; identities are never merged by email alone.
export const principals = pgTable("principals", {
  id: text("id").primaryKey(),
  kind: text("kind").notNull().default("human"),
  displayName: text("display_name").notNull(),
  primaryEmail: text("primary_email"),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [check("principals_kind_ck", sql`${table.kind} in ('human','service')`)]);

export const identityLinks = pgTable("identity_links", {
  id: text("id").primaryKey(),
  principalId: text("principal_id").notNull().references(() => principals.id),
  provider: text("provider").notNull(),
  subject: text("subject").notNull(),
  emailAtLink: text("email_at_link"),
  emailVerified: boolean("email_verified").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: "date" }),
}, (table) => [
  uniqueIndex("identity_links_provider_subject_uq").on(table.provider, table.subject),
  index("identity_links_principal_idx").on(table.principalId),
]);

export const organizations = pgTable("organizations", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  ownerUserId: text("owner_user_id").notNull(),
  // Which connected model-provider ProviderId (integration_connections.provider,
  // category "Model") powers agents/Ask Aval for this org. Null means model
  // features are paused until a provider is connected and selected.
  activeModelProvider: text("active_model_provider"),
  // Which persona (a built-in PersonaId or a custom_personas row's id) Ask
  // Aval opens with by default for this org — set from Settings → Aval
  // Setup. Null means the built-in "general" persona, matching this app's
  // behavior before this column existed.
  defaultPersonaId: text("default_persona_id"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
});

export const ssoConnections = pgTable("sso_connections", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  supabaseProviderId: text("supabase_provider_id"),
  permittedDomainsJson: jsonb("permitted_domains_json").notNull().default([]),
  enforcement: text("enforcement").notNull().default("disabled"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("sso_connections_org_uq").on(table.organizationId),
  check("sso_connections_enforcement_ck", sql`${table.enforcement} in ('disabled','optional','required')`),
]);

/**
 * Who belongs to a workspace, and what they may do in it.
 *
 * Until this existed, `organizationIdForUser` hashed a user id into a
 * workspace, so every account was alone in its own. Two controls depended on a
 * second person who could not exist: the elevated approval tier requires two
 * distinct approvers, and separation of duties forbids the requester from
 * approving a critical action. Both failed closed — safe, but it meant the
 * approval gate could never open for the actions it exists to gate.
 *
 * A user's personal workspace is still `org_<hash(userId)>` and is not
 * migrated; membership is additive. A row here is what lets someone act in a
 * workspace that is not their own.
 */
export const organizationMembers = pgTable(
  "organization_members",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    userId: text("user_id").notNull().references(() => users.id),
    // owner: policy, invitations, membership, approvals.
    // approver: approvals, plus everything a member may do.
    // member: run agents and read; never decides an approval.
    role: text("role").notNull(),
    invitedByUserId: text("invited_by_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    // One membership per person per workspace. This is also what makes
    // "two distinct approvers" countable rather than a matter of trust.
    uniqueIndex("organization_members_org_user_uq").on(table.organizationId, table.userId),
    index("organization_members_user_idx").on(table.userId),
  ],
);

/**
 * An outstanding invitation to a workspace.
 *
 * There is no email service in this deployment, so the code is shown to the
 * inviter once and shared out of band. Only its hash is stored: an invitation
 * grants standing access to a tenant's data, which makes it a credential, and
 * a credential readable from a database row is one a database read can steal.
 */
export const organizationInvitations = pgTable(
  "organization_invitations",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    codeHash: text("code_hash").notNull(),
    role: text("role").notNull(),
    createdByUserId: text("created_by_user_id").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    acceptedByUserId: text("accepted_by_user_id"),
    acceptedAt: timestamp("accepted_at", { withTimezone: true, mode: "date" }),
    revokedAt: timestamp("revoked_at", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    // The lookup is by hash, and uniqueness stops one code being redeemed
    // twice through concurrent requests.
    uniqueIndex("organization_invitations_code_uq").on(table.codeHash),
    index("organization_invitations_org_idx").on(table.organizationId, table.createdAt),
  ],
);

export const integrationConnections = pgTable(
  "integration_connections",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    provider: text("provider").notNull(),
    category: text("category").notNull(),
    status: text("status").notNull().default("pending"),
    authMode: text("auth_mode").notNull(),
    externalAccountId: text("external_account_id"),
    externalAccountName: text("external_account_name"),
    scopesJson: jsonb("scopes_json").notNull().default([]),
    accessTokenCiphertext: text("access_token_ciphertext"),
    refreshTokenCiphertext: text("refresh_token_ciphertext"),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }),
    metadataJson: jsonb("metadata_json").notNull().default({}),
    lastSyncAt: timestamp("last_sync_at", { withTimezone: true, mode: "date" }),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("integration_connections_org_provider_uq").on(table.organizationId, table.provider),
    index("integration_connections_org_status_idx").on(table.organizationId, table.status),
  ],
);

export const oauthStates = pgTable(
  "oauth_states",
  {
    state: text("state").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    provider: text("provider").notNull(),
    userId: text("user_id").notNull(),
    codeVerifier: text("code_verifier"),
    returnTo: text("return_to").notNull().default("/?view=connections"),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("oauth_states_expiry_idx").on(table.expiresAt)],
);

export const integrationEvents = pgTable(
  "integration_events",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id"),
    connectionId: text("connection_id").references(() => integrationConnections.id),
    provider: text("provider").notNull(),
    externalEventId: text("external_event_id").notNull(),
    eventType: text("event_type").notNull(),
    payloadJson: jsonb("payload_json").notNull(),
    status: text("status").notNull().default("received"),
    receivedAt: timestamp("received_at", { withTimezone: true, mode: "date" }).notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [
    uniqueIndex("integration_events_provider_external_uq").on(table.provider, table.externalEventId),
    index("integration_events_provider_status_idx").on(table.provider, table.status),
  ],
);

export const syncRuns = pgTable(
  "sync_runs",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    connectionId: text("connection_id").notNull().references(() => integrationConnections.id),
    provider: text("provider").notNull(),
    status: text("status").notNull().default("queued"),
    cursorJson: jsonb("cursor_json").notNull().default({}),
    countsJson: jsonb("counts_json").notNull().default({}),
    error: text("error"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }).notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [index("sync_runs_connection_started_idx").on(table.connectionId, table.startedAt)],
);

/** Durable, opt-in import scheduling and per-connection worker lease. */
export const integrationSyncState = pgTable("integration_sync_state", {
  connectionId: text("connection_id").primaryKey().references(() => integrationConnections.id),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  externalAccountId: text("external_account_id").notNull(),
  enabled: boolean("enabled").notNull().default(true),
  cursorJson: jsonb("cursor_json").notNull().default({}),
  nextRunAt: timestamp("next_run_at", { withTimezone: true, mode: "date" }).notNull(),
  leaseToken: text("lease_token"),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true, mode: "date" }),
  attempts: integer("attempts").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [index("integration_sync_due_idx").on(table.enabled, table.nextRunAt)]);

export const conversations = pgTable(
  "conversations",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    channel: text("channel").notNull(),
    externalThreadId: text("external_thread_id").notNull(),
    contactDisplayName: text("contact_display_name").notNull(),
    status: text("status").notNull().default("open"),
    locale: text("locale").notNull().default("en"),
    register: text("register").notNull().default("professional"),
    // A reply Ask Aval drafted the moment the latest inbound message arrived
    // (lib/ask-aval/auto-reply.ts), pre-filled in the Inbox composer for a
    // human to edit or send. Never sent automatically — see draftReplyStatus.
    draftReply: text("draft_reply"),
    draftReplyStatus: text("draft_reply_status"),
    draftReplyAt: timestamp("draft_reply_at", { withTimezone: true, mode: "date" }),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true, mode: "date" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("conversations_org_channel_external_uq").on(table.organizationId, table.channel, table.externalThreadId),
    index("conversations_org_status_idx").on(table.organizationId, table.status),
  ],
);

export const messages = pgTable(
  "messages",
  {
    id: text("id").primaryKey(),
    conversationId: text("conversation_id").notNull().references(() => conversations.id),
    externalMessageId: text("external_message_id").notNull(),
    direction: text("direction").notNull(),
    body: text("body").notNull(),
    payloadJson: jsonb("payload_json").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("messages_conversation_external_uq").on(table.conversationId, table.externalMessageId),
    index("messages_conversation_created_idx").on(table.conversationId, table.createdAt),
  ],
);

export const portfolioSnapshots = pgTable(
  "portfolio_snapshots",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    source: text("source").notNull(),
    metricKey: text("metric_key").notNull(),
    numericValue: integer("numeric_value"),
    textValue: text("text_value"),
    periodStart: timestamp("period_start", { withTimezone: true, mode: "date" }),
    periodEnd: timestamp("period_end", { withTimezone: true, mode: "date" }),
    capturedAt: timestamp("captured_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("portfolio_snapshots_org_captured_idx").on(table.organizationId, table.capturedAt)],
);

export const funnelSnapshots = pgTable(
  "funnel_snapshots",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    source: text("source").notNull(),
    stage: text("stage").notNull(),
    count: integer("count").notNull(),
    capturedAt: timestamp("captured_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("funnel_snapshots_org_captured_idx").on(table.organizationId, table.capturedAt)],
);

// Ask Aval's daily spend guard: one row per model call, so a per-org daily
// cap can be enforced by counting rows for today rather than trusting an
// in-memory counter that a Worker isolate wouldn't reliably persist anyway.
export const aiUsage = pgTable(
  "ai_usage",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    userId: text("user_id").notNull(),
    day: text("day").notNull(),
    inputTokens: bigint("input_tokens", { mode: "number" }).notNull().default(0),
    outputTokens: bigint("output_tokens", { mode: "number" }).notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("ai_usage_org_day_idx").on(table.organizationId, table.day)],
);

// One row per org, tracking its current Stripe subscription. planId is a
// key into lib/billing/plans.ts's PLANS array, not a foreign key: plans are
// defined in code, not the database, since they change by editing that
// file rather than running a migration.
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    planId: text("plan_id").notNull(),
    status: text("status").notNull(),
    stripeCustomerId: text("stripe_customer_id"),
    stripeSubscriptionId: text("stripe_subscription_id"),
    currentPeriodStart: timestamp("current_period_start", { withTimezone: true, mode: "date" }),
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [uniqueIndex("subscriptions_org_uq").on(table.organizationId)],
);

// One row per completed one-time "buy more tokens" purchase. Token balance
// is the sum of tokensGranted across all rows for an org, not a running
// counter column, so a webhook retried by Stripe (deduplicated on
// stripeSessionId) can never double- or under-credit a purchase.
export const tokenTopUps = pgTable(
  "token_top_ups",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    stripeSessionId: text("stripe_session_id").notNull(),
    packId: text("pack_id").notNull(),
    tokensGranted: integer("tokens_granted").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [uniqueIndex("token_top_ups_session_uq").on(table.stripeSessionId)],
);

// Every finished (or failed) Ask Aval Tasks draft, so a refresh doesn't lose
// it — the client's draft-job state is otherwise purely in-memory.
export const draftDocuments = pgTable(
  "draft_documents",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    userId: text("user_id").notNull(),
    title: text("title").notNull(),
    instructions: text("instructions").notNull(),
    format: text("format").notNull(),
    status: text("status").notNull(),
    headline: text("headline"),
    narrative: text("narrative"),
    documentType: text("document_type"),
    documentMarkdown: text("document_markdown"),
    metricsJson: jsonb("metrics_json").notNull().default([]),
    chartJson: jsonb("chart_json"),
    confidence: text("confidence"),
    errorMessage: text("error_message"),
    sentTo: text("sent_to"),
    moduleLabel: text("module_label"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("draft_documents_org_created_idx").on(table.organizationId, table.createdAt)],
);

// A structured, redacted workflow preference — never raw tenant/financial
// content — that Ask Aval reads back as context. See
// lib/ask-aval/preferences.ts for what is and isn't allowed to land here.
export const learnedPreferences = pgTable(
  "learned_preferences",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    topic: text("topic").notNull(),
    statement: text("statement").notNull(),
    source: text("source").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("learned_preferences_org_topic_uq").on(table.organizationId, table.topic),
    index("learned_preferences_org_idx").on(table.organizationId),
  ],
);

// One run per triggered automation (e.g. a maintenance issue routed to a
// vendor). insightId ties back to the real sample insight that triggered
// it — no synthetic trigger data.
export const automationRuns = pgTable(
  "automation_runs",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    insightId: text("insight_id").notNull(),
    status: text("status").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("automation_runs_org_created_idx").on(table.organizationId, table.createdAt)],
);

// Each timeline entry within a run, in order.
export const automationSteps = pgTable(
  "automation_steps",
  {
    id: text("id").primaryKey(),
    runId: text("run_id").notNull().references(() => automationRuns.id),
    kind: text("kind").notNull(),
    actorLabel: text("actor_label").notNull(),
    summary: text("summary").notNull(),
    payloadJson: jsonb("payload_json").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("automation_steps_run_idx").on(table.runId)],
);

// One row per rate-limited attempt (signup, login), never per-window —
// counted by querying rows within the window, the same idiom ai_usage
// already uses for the daily model-call cap, so the limiter needs no
// separate counter that a Worker isolate wouldn't reliably persist anyway.
// scopeKey encodes both the action and the identity being limited (e.g.
// "signup:ip:203.0.113.4" or "login:email:a@b.com") so IP-based and
// account-based limits can coexist without cross-contaminating.
export const rateLimitHits = pgTable(
  "rate_limit_hits",
  {
    id: text("id").primaryKey(),
    scopeKey: text("scope_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("rate_limit_hits_scope_created_idx").on(table.scopeKey, table.createdAt)],
);

// One row per approve/deny/send decision on an actionable insight — the
// richest real usage signal in the app, previously only client-side state
// that vanished on refresh and was invisible to Ask Aval. insightId and
// decision are both from a small fixed set (never free text), so this
// stays as privacy-safe as learned_preferences by construction, not by
// filtering: there is no field here a tenant name or dollar amount could
// end up in. See lib/ask-aval/usage-patterns.ts for how this is read back.
export const insightDecisions = pgTable(
  "insight_decisions",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    insightId: text("insight_id").notNull(),
    decision: text("decision").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("insight_decisions_org_insight_idx").on(table.organizationId, table.insightId)],
);

// A physical (or, pre-connection, manually tracked) electricity/water/gas
// meter. There is no `properties`/`units` table yet — see docs/DECISIONS.md
// — so meters are scoped to the org with a free-text property/unit label,
// the same shape `insightDecisions` uses above for referencing a sample-data
// id that doesn't have a real table behind it yet. Once a real property
// table exists, propertyLabel/unitLabel should become propertyId/unitId.
export const utilityMeters = pgTable(
  "utility_meters",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    utilityType: text("utility_type").notNull(), // "electricity" | "water" | "gas"
    propertyLabel: text("property_label").notNull(),
    unitLabel: text("unit_label"),
    meterNumber: text("meter_number"),
    provider: text("provider"),
    unitOfMeasure: text("unit_of_measure").notNull(), // "kWh" | "gal" | "ccf" | "therm" | "m3"
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("utility_meters_org_type_idx").on(table.organizationId, table.utilityType)],
);

// One row per billing-period read for a meter. usageAmount is a `real`
// column since utility usage is fractional (1,234.56 kWh); costCents stays
// an integer, matching how money is stored everywhere else in this schema
// (see `tokenTopUps`, billing) — see lib/finance/money.ts for the
// dinero.js-backed arithmetic that operates on it.
export const utilityBills = pgTable(
  "utility_bills",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    meterId: text("meter_id").notNull().references(() => utilityMeters.id),
    periodStart: timestamp("period_start", { withTimezone: true, mode: "date" }).notNull(),
    periodEnd: timestamp("period_end", { withTimezone: true, mode: "date" }).notNull(),
    usageAmount: numeric("usage_amount", { precision: 20, scale: 6, mode: "number" }).notNull(),
    costCents: bigint("cost_cents", { mode: "number" }).notNull(),
    currency: text("currency").notNull().default("USD"),
    source: text("source").notNull(), // "manual" | "ai_extracted"
    extractionConfidence: text("extraction_confidence"), // set only when source is "ai_extracted"
    extractionNote: text("extraction_note"), // model's own caveat about the extraction, shown to the user, never trusted silently
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    index("utility_bills_org_period_idx").on(table.organizationId, table.periodStart),
    index("utility_bills_meter_period_idx").on(table.meterId, table.periodStart),
  ],
);

// A workspace-defined Ask Aval persona, alongside the fixed built-in roster
// in lib/ask-aval/personas.ts (general/financial/brokerage/realEstate/
// marketResearch/maintenance). focusDescription becomes a system-prompt
// *addition*, never a replacement — see lib/ask-aval/custom-personas.ts for
// why an operator-authored focus can't be used to bypass the faithfulness
// gate or reach a tool outside toolNamesJson, regardless of its wording.
export const agentPersonas = pgTable(
  "agent_personas",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    label: text("label").notNull(),
    focusDescription: text("focus_description").notNull(),
    toolNamesJson: jsonb("tool_names_json"), // JSON string array, or null meaning "every tool" (matches AgentPersona.toolNames)
    shape: text("shape").notNull(), // ShapeId, app/components/agent-avatar/shapes.tsx
    theme: text("theme").notNull(), // ThemeId, app/components/agent-avatar/themes.ts
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("agent_personas_org_idx").on(table.organizationId)],
);

// A tamper-evident record of what Ask Aval did to produce each answer: which
// tools ran, whether the faithfulness gate passed, and a digest of the answer.
// Each row commits to the previous row's hash (see lib/audit/chain.ts), so the
// trail can be re-verified and any edit, deletion or reordering surfaces.
//
// Deliberately stores DIGESTS, not payloads. Tool results carry resident names
// and balances; keeping them here would make this table a second, indefinitely
// retained copy of the most sensitive data in the app. `label` holds only a
// tool name or a gate outcome, and `count` only a magnitude — neither is
// identifying. Same trade as learned_preferences: keep the structure, drop the
// content.
export const answerAuditLog = pgTable(
  "answer_audit_log",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    // 1-based, contiguous per organization — a gap is itself evidence.
    sequence: integer("sequence").notNull(),
    kind: text("kind").notNull(), // AuditEntryKind
    label: text("label").notNull(),
    payloadDigest: text("payload_digest").notNull(),
    count: integer("count").notNull(),
    previousHash: text("previous_hash").notNull(),
    entryHash: text("entry_hash").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    // Enforces contiguity at the database level: two concurrent runs cannot
    // both claim the same position, so a race fails loudly instead of forking
    // the chain into two branches that each look valid alone.
    uniqueIndex("answer_audit_log_org_sequence_uq").on(table.organizationId, table.sequence),
    index("answer_audit_log_org_idx").on(table.organizationId),
  ],
);

// Documents a workspace pastes in for Aval to read: leases, owner and lender
// statements, vendor estimates. This is the ingestion layer two deferred agent
// ideas needed (docs/DECISIONS.md) — document financial extraction, and a
// lease-review persona that can answer about a specific contract.
//
// Unlike learned_preferences and answer_audit_log, this table DOES hold raw
// third-party text, because that is the whole point: you cannot review a lease
// without the lease. The controls are therefore explicit rather than
// structural — org scoping like every other row, a hard size cap, and
// user-initiated deletion — and `lib/ask-aval/handler.ts`'s standing rule that
// tool output is data and never instructions matters more here than anywhere
// else, since a lease is authored by someone outside the workspace.
export const documents = pgTable(
  "documents",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    title: text("title").notNull(),
    kind: text("kind").notNull(), // DocumentKind, lib/documents/types.ts
    contentText: text("content_text").notNull(),
    // Denormalized so the list view can show size without reading every body.
    charCount: integer("char_count").notNull(),
    uploadedBy: text("uploaded_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [index("documents_org_idx").on(table.organizationId)],
);

export const ownershipEntities = pgTable("ownership_entities", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  name: text("name").notNull(),
  legalName: text("legal_name"),
  externalId: text("external_id"),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("ownership_entities_org_id_uq").on(table.organizationId, table.id),
  uniqueIndex("ownership_entities_org_external_uq").on(table.organizationId, table.externalId),
]);

export const portfolios = pgTable("portfolios", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  name: text("name").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("portfolios_org_id_uq").on(table.organizationId, table.id),
  uniqueIndex("portfolios_org_name_uq").on(table.organizationId, table.name),
]);

export const regions = pgTable("regions", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  name: text("name").notNull(),
  code: text("code"),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("regions_org_id_uq").on(table.organizationId, table.id),
  uniqueIndex("regions_org_code_uq").on(table.organizationId, table.code),
]);

/* ═══════════════════════════════════════════════════════════════════════════
 * OPERATIONS
 *
 * The canonical record layer behind the Operations module (Properties,
 * Leasing, Maintenance, Accounting). Until now this app stored only
 * `portfolio_snapshots` — a flat metric_key → number table — which can report
 * "occupancy is 94%" but cannot answer which unit type is slowest to lease,
 * which vendor misses its SLA, or who is 60 days past due. Those questions
 * need records, not pre-aggregated metrics, so these tables hold records and
 * every figure the app shows is computed from them (lib/operations/).
 *
 * Three decisions run through all of it:
 *
 * 1. ONE VOCABULARY, MANY SOURCES. A portfolio is rarely on one system —
 *    leasing in AppFolio, books in QuickBooks, work orders somewhere else.
 *    These tables are the normalized shape everything lands in, so figures
 *    aggregate across a mixed stack instead of per-connector. Field names
 *    follow the MITS/NMHC domains (Property-Marketing, Lease/Application,
 *    Resident Transactions, Lead Management) that the real connectors
 *    ultimately map from.
 *
 * 2. PROVENANCE ON EVERY ROW. `sourceProvider` + `externalId` say where a row
 *    came from ("manual" when a person typed it), and their unique index per
 *    org makes re-syncing an upsert rather than a duplicate. A number with no
 *    traceable origin is not something this app is willing to show.
 *
 * 3. DISAGREEMENTS ARE RECORDED, NEVER SILENTLY RESOLVED. When two connected
 *    systems report different values for the same field, `operations_conflicts`
 *    keeps both and flags it. Picking a winner invisibly is how a dashboard
 *    ends up confidently wrong — the same failure the faithfulness gate and
 *    audit chain exist to prevent, one layer lower down.
 *
 * Money is integer cents everywhere, matching the rest of this schema; see
 * lib/finance/money.ts for the arithmetic.
 * ═══════════════════════════════════════════════════════════════════════════ */

export const properties = pgTable(
  "properties",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    ownershipEntityId: text("ownership_entity_id").references(() => ownershipEntities.id),
    portfolioId: text("portfolio_id").references(() => portfolios.id),
    regionId: text("region_id").references(() => regions.id),
    name: text("name").notNull(),
    addressLine1: text("address_line1"),
    city: text("city"),
    region: text("region"),
    postalCode: text("postal_code"),
    country: text("country").notNull().default("US"),
    propertyType: text("property_type").notNull().default("multifamily"), // PropertyType, lib/operations/types.ts
    // What the source system *says* the unit count is, which is not always the
    // number of unit rows it actually delivered. Kept separate from the derived
    // count rather than reconciled on write: a mismatch is a real finding about
    // an incomplete sync, and overwriting one with the other would hide it.
    reportedUnitCount: integer("reported_unit_count"),
    yearBuilt: integer("year_built"),
    squareFeet: integer("square_feet"),
    // Present only where a source or the operator supplied them; cap-rate and
    // valuation math is skipped rather than estimated when they are null.
    acquisitionCostCents: bigint("acquisition_cost_cents", { mode: "number" }),
    currentValueCents: bigint("current_value_cents", { mode: "number" }),
    status: text("status").notNull().default("active"), // "active" | "inactive"
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("properties_org_id_uq").on(table.organizationId, table.id),
    uniqueIndex("properties_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("properties_org_status_idx").on(table.organizationId, table.status),
    foreignKey({ columns: [table.organizationId, table.ownershipEntityId], foreignColumns: [ownershipEntities.organizationId, ownershipEntities.id], name: "properties_org_owner_fk" }),
    foreignKey({ columns: [table.organizationId, table.portfolioId], foreignColumns: [portfolios.organizationId, portfolios.id], name: "properties_org_portfolio_fk" }),
    foreignKey({ columns: [table.organizationId, table.regionId], foreignColumns: [regions.organizationId, regions.id], name: "properties_org_region_fk" }),
  ],
);

export const accessGrants = pgTable("access_grants", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  principalId: text("principal_id").notNull().references(() => principals.id),
  role: text("role").notNull(),
  organizationScope: boolean("organization_scope").notNull().default(false),
  ownershipEntityId: text("ownership_entity_id").references(() => ownershipEntities.id),
  portfolioId: text("portfolio_id").references(() => portfolios.id),
  regionId: text("region_id").references(() => regions.id),
  propertyId: text("property_id").references(() => properties.id),
  capabilitiesJson: jsonb("capabilities_json").notNull().default([]),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }),
  revokedAt: timestamp("revoked_at", { withTimezone: true, mode: "date" }),
  createdByPrincipalId: text("created_by_principal_id").references(() => principals.id),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("access_grants_org_id_uq").on(table.organizationId, table.id),
  index("access_grants_principal_org_idx").on(table.principalId, table.organizationId),
  index("access_grants_property_idx").on(table.organizationId, table.propertyId),
  check("access_grants_role_ck", sql`${table.role} in ('org_admin','regional_manager','property_manager','approver','operator','viewer','owner_viewer')`),
  check("access_grants_one_scope_ck", sql`
    (case when ${table.organizationScope} then 1 else 0 end) +
    (case when ${table.ownershipEntityId} is not null then 1 else 0 end) +
    (case when ${table.portfolioId} is not null then 1 else 0 end) +
    (case when ${table.regionId} is not null then 1 else 0 end) +
    (case when ${table.propertyId} is not null then 1 else 0 end) = 1
  `),
  foreignKey({ columns: [table.organizationId, table.ownershipEntityId], foreignColumns: [ownershipEntities.organizationId, ownershipEntities.id], name: "access_grants_org_owner_fk" }),
  foreignKey({ columns: [table.organizationId, table.portfolioId], foreignColumns: [portfolios.organizationId, portfolios.id], name: "access_grants_org_portfolio_fk" }),
  foreignKey({ columns: [table.organizationId, table.regionId], foreignColumns: [regions.organizationId, regions.id], name: "access_grants_org_region_fk" }),
  foreignKey({ columns: [table.organizationId, table.propertyId], foreignColumns: [properties.organizationId, properties.id], name: "access_grants_org_property_fk" }),
]);

export const approvalAuthorities = pgTable("approval_authorities", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  accessGrantId: text("access_grant_id").notNull().references(() => accessGrants.id),
  action: text("action").notNull(),
  currency: text("currency").notNull().default("USD"),
  maximumAmountCents: bigint("maximum_amount_cents", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (table) => [
  uniqueIndex("approval_authorities_grant_action_currency_uq").on(table.accessGrantId, table.action, table.currency),
  check("approval_authorities_amount_ck", sql`${table.maximumAmountCents} >= 0`),
  foreignKey({ columns: [table.organizationId, table.accessGrantId], foreignColumns: [accessGrants.organizationId, accessGrants.id], name: "approval_authorities_org_grant_fk" }),
]);

export const units = pgTable(
  "units",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    propertyId: text("property_id").notNull().references(() => properties.id),
    unitNumber: text("unit_number").notNull(),
    bedrooms: integer("bedrooms"),
    bathrooms: doublePrecision("bathrooms"), // real: 1.5-bath units are ordinary
    squareFeet: integer("square_feet"),
    // The asking rent for this unit today. Distinct from the rent on its
    // active lease, and the difference between them is loss-to-lease — a
    // figure operators care about that is invisible if only one is stored.
    marketRentCents: bigint("market_rent_cents", { mode: "number" }),
    status: text("status").notNull().default("vacant_ready"), // UnitStatus, lib/operations/types.ts
    // Set when the unit last went vacant, so days-vacant is measured rather
    // than guessed. Null for a unit that has never turned over here.
    vacantSince: timestamp("vacant_since", { withTimezone: true, mode: "date" }),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("units_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("units_org_property_idx").on(table.organizationId, table.propertyId),
    index("units_org_status_idx").on(table.organizationId, table.status),
  ],
);

// A person on a lease or an application. Holds contact details because
// collections and leasing both need a channel to reach someone on — this is
// the one operations table carrying personal data, and it is org-scoped and
// never written into learned_preferences or the audit log (which store
// digests and tags precisely so they cannot become a second copy of this).
export const residents = pgTable(
  "residents",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    displayName: text("display_name").notNull(),
    email: text("email"),
    phone: text("phone"),
    status: text("status").notNull().default("current"), // ResidentStatus, lib/operations/types.ts
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("residents_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("residents_org_status_idx").on(table.organizationId, table.status),
  ],
);

export const leases = pgTable(
  "leases",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    unitId: text("unit_id").notNull().references(() => units.id),
    propertyId: text("property_id").notNull().references(() => properties.id), // denormalized so portfolio rollups don't join through units
    status: text("status").notNull().default("active"), // LeaseStatus, lib/operations/types.ts
    startDate: timestamp("start_date", { withTimezone: true, mode: "date" }).notNull(),
    // Null for month-to-month, which is why isMonthToMonth exists separately:
    // a null end date otherwise reads identically to "we didn't get one".
    endDate: timestamp("end_date", { withTimezone: true, mode: "date" }),
    isMonthToMonth: boolean("is_month_to_month").notNull().default(false),
    moveInDate: timestamp("move_in_date", { withTimezone: true, mode: "date" }),
    moveOutDate: timestamp("move_out_date", { withTimezone: true, mode: "date" }),
    rentCents: bigint("rent_cents", { mode: "number" }).notNull(),
    // Held on behalf of the resident, not revenue. Kept on the lease and
    // mirrored into a trust-flagged GL account rather than mixed into
    // operating income — most states require the separation, and the ledger
    // categorizes deposits apart from rent for the same reason.
    depositCents: bigint("deposit_cents", { mode: "number" }).notNull().default(0),
    rentDueDay: integer("rent_due_day").notNull().default(1),
    // Points at the lease this one renewed, so renewal rate is counted from
    // records rather than inferred from dates lining up.
    renewalOfLeaseId: text("renewal_of_lease_id"),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("leases_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("leases_org_status_idx").on(table.organizationId, table.status),
    index("leases_org_end_idx").on(table.organizationId, table.endDate),
    index("leases_unit_idx").on(table.unitId),
  ],
);

// Many-to-many: a lease routinely has co-residents and guarantors, and
// collapsing them to a single "tenant name" column loses whoever else is
// actually liable for the balance.
export const leaseResidents = pgTable(
  "lease_residents",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    leaseId: text("lease_id").notNull().references(() => leases.id),
    residentId: text("resident_id").notNull().references(() => residents.id),
    role: text("role").notNull().default("primary"), // "primary" | "co_resident" | "guarantor"
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("lease_residents_lease_resident_uq").on(table.leaseId, table.residentId),
    index("lease_residents_org_idx").on(table.organizationId),
  ],
);

// The receivables spine: one row per charge, payment, credit or refund
// against a lease. Delinquency and AR aging are derived by walking these
// rows, never stored as a balance column — a stored balance drifts from its
// own history the first time a row is corrected, and then the number on
// screen has no way to be checked.
//
// `amountCents` is always POSITIVE; `entryType` carries the direction. A
// signed column invites a sign bug that silently turns a payment into a
// charge, and a negative number in a ledger export is ambiguous besides.
export const ledgerEntries = pgTable(
  "ledger_entries",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    leaseId: text("lease_id").notNull().references(() => leases.id),
    propertyId: text("property_id").notNull().references(() => properties.id), // denormalized for property-level AR without a join
    entryType: text("entry_type").notNull(), // LedgerEntryType: "charge" | "payment" | "credit" | "refund"
    category: text("category").notNull(), // LedgerCategory: "rent" | "deposit" | "late_fee" | "utility" | "other"
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: text("currency").notNull().default("USD"),
    postedAt: timestamp("posted_at", { withTimezone: true, mode: "date" }).notNull(),
    // Charges only — the date aging is measured from. Null on payments, which
    // are not owed on a date.
    dueAt: timestamp("due_at", { withTimezone: true, mode: "date" }),
    memo: text("memo"),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("ledger_entries_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("ledger_entries_org_lease_idx").on(table.organizationId, table.leaseId),
    index("ledger_entries_org_posted_idx").on(table.organizationId, table.postedAt),
    index("ledger_entries_org_due_idx").on(table.organizationId, table.dueAt),
  ],
);

export const vendors = pgTable(
  "vendors",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    name: text("name").notNull(),
    trade: text("trade"), // free text: the trades a portfolio uses are not a closed set
    email: text("email"),
    phone: text("phone"),
    // Compliance, not trivia: an expired COI on an assigned vendor is a
    // liability an operator wants surfaced before the work is booked.
    insuranceExpiresAt: timestamp("insurance_expires_at", { withTimezone: true, mode: "date" }),
    isActive: boolean("is_active").notNull().default(true),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("vendors_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("vendors_org_active_idx").on(table.organizationId, table.isActive),
  ],
);

// One row per maintenance request. The four lifecycle timestamps are separate
// columns rather than a status-change log because every maintenance metric
// operators actually use is a difference between two of them — response time
// (reported→assigned), time to repair (reported→completed), and a vendor's
// own turnaround (assigned→completed). A status field alone can say a work
// order is closed but never how long it took.
export const workOrders = pgTable(
  "work_orders",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    propertyId: text("property_id").notNull().references(() => properties.id),
    unitId: text("unit_id").references(() => units.id), // null for common-area work
    leaseId: text("lease_id").references(() => leases.id), // who reported it, when a resident did
    category: text("category").notNull().default("general"), // WorkOrderCategory, lib/operations/types.ts
    priority: text("priority").notNull().default("routine"), // WorkOrderPriority — drives the SLA target
    status: text("status").notNull().default("reported"), // WorkOrderStatus
    summary: text("summary").notNull(),
    reportedAt: timestamp("reported_at", { withTimezone: true, mode: "date" }).notNull(),
    assignedAt: timestamp("assigned_at", { withTimezone: true, mode: "date" }),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", { withTimezone: true, mode: "date" }),
    vendorId: text("vendor_id").references(() => vendors.id),
    estimateCents: bigint("estimate_cents", { mode: "number" }),
    actualCostCents: bigint("actual_cost_cents", { mode: "number" }),
    // Set when this work order is a return visit for work already done —
    // the raw material for first-time-fix rate, which the maintenance
    // research identifies as the single metric most tied to vendor cost.
    // Recorded explicitly rather than guessed from "same unit, same category,
    // within 30 days", which would count two genuinely different faults as a
    // callback.
    callbackOfWorkOrderId: text("callback_of_work_order_id"),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("work_orders_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("work_orders_org_status_idx").on(table.organizationId, table.status),
    index("work_orders_org_reported_idx").on(table.organizationId, table.reportedAt),
    index("work_orders_org_vendor_idx").on(table.organizationId, table.vendorId),
    index("work_orders_org_property_idx").on(table.organizationId, table.propertyId),
  ],
);

// Chart of accounts. Kept in the database rather than in code (unlike
// lib/billing/plans.ts) because it is the customer's chart, mirrored from
// their accounting system — every portfolio numbers and names it differently.
export const glAccounts = pgTable(
  "gl_accounts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    code: text("code").notNull(), // e.g. "4000", "6120"
    name: text("name").notNull(),
    accountType: text("account_type").notNull(), // GlAccountType, lib/operations/types.ts
    // Client money — deposits and owner funds — which most states require be
    // held separately from operating funds. Flagged here so a P&L rollup can
    // exclude it by construction instead of by remembering to.
    isTrustAccount: boolean("is_trust_account").notNull().default(false),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("gl_accounts_org_code_uq").on(table.organizationId, table.code),
    index("gl_accounts_org_type_idx").on(table.organizationId, table.accountType),
  ],
);

// Posted amounts against a GL account, optionally attributed to a property.
//
// This is a REPORTING ledger, not a double-entry book of record: one row per
// posted amount, positive in the account's own natural direction (income rows
// are revenue, expense rows are spend). Aval reads books it does not keep —
// modeling debits and credits would imply this app could be the system of
// record for someone's accounting, which it is not and should not claim.
export const glTransactions = pgTable(
  "gl_transactions",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    accountId: text("account_id").notNull().references(() => glAccounts.id),
    propertyId: text("property_id").references(() => properties.id), // null for portfolio-level or unallocated entries
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: text("currency").notNull().default("USD"),
    postedAt: timestamp("posted_at", { withTimezone: true, mode: "date" }).notNull(),
    memo: text("memo"),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("gl_transactions_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("gl_transactions_org_posted_idx").on(table.organizationId, table.postedAt),
    index("gl_transactions_org_property_idx").on(table.organizationId, table.propertyId),
  ],
);

// One row per prospect, with a timestamp per stage reached.
//
// This is what `funnel_snapshots` cannot be. That table stores a count per
// stage per capture, which answers "how many applied last week" and nothing
// else. Stage timestamps on a record answer the questions operators actually
// act on: where the funnel drops off, how long each step takes, and which
// unit types sit longest — the leasing-velocity metrics the 2026 multifamily
// research puts at the top. Both tables stay: snapshots remain the cheap
// shape for a connector that only exposes aggregates.
export const leasingLeads = pgTable(
  "leasing_leads",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    propertyId: text("property_id").references(() => properties.id),
    unitId: text("unit_id").references(() => units.id),
    residentId: text("resident_id").references(() => residents.id), // set once a prospect becomes a person on a lease
    // Where the lead came from (ILS, website, referral, walk-in). Free text
    // rather than an enum: channel names differ per market and per connector,
    // and an unrecognized channel should still be counted, not dropped.
    channel: text("channel"),
    // The unit type asked for, as a label ("2BR/1BA"). Days-to-lease is only
    // actionable broken out this way — a portfolio-wide average hides that
    // studios move in a week and three-beds sit for two months.
    unitTypeLabel: text("unit_type_label"),
    stage: text("stage").notNull().default("inquiry"), // LeadStage, lib/operations/types.ts
    inquiredAt: timestamp("inquired_at", { withTimezone: true, mode: "date" }).notNull(),
    contactedAt: timestamp("contacted_at", { withTimezone: true, mode: "date" }),
    touredAt: timestamp("toured_at", { withTimezone: true, mode: "date" }),
    appliedAt: timestamp("applied_at", { withTimezone: true, mode: "date" }),
    approvedAt: timestamp("approved_at", { withTimezone: true, mode: "date" }),
    signedAt: timestamp("signed_at", { withTimezone: true, mode: "date" }),
    lostAt: timestamp("lost_at", { withTimezone: true, mode: "date" }),
    lostReason: text("lost_reason"),
    sourceProvider: text("source_provider").notNull().default("manual"),
    sourceConnectionId: text("source_connection_id").references(() => integrationConnections.id),
    externalId: text("external_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("leasing_leads_org_source_external_uq").on(table.organizationId, table.sourceProvider, table.externalId),
    index("leasing_leads_org_stage_idx").on(table.organizationId, table.stage),
    index("leasing_leads_org_inquired_idx").on(table.organizationId, table.inquiredAt),
  ],
);

// Two connected systems describing the same thing differently.
//
// The premise of connecting a portfolio's whole stack is that the pieces
// disagree — a PMS and an accounting system will not report the same rent for
// the same unit forever. The tempting behavior is last-write-wins, which
// produces a dashboard that is confidently wrong and gives a user no way to
// notice. So a differing value from a different source is written HERE and the
// stored row is left alone; the operator decides, and until they do, readers
// can see the field is contested.
//
// Holds values as text (`valueA`/`valueB`) because it spans every field type
// in the operations model, and it is a record of what each system said rather
// than something arithmetic is done on.
export const operationsConflicts = pgTable(
  "operations_conflicts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    entityType: text("entity_type").notNull(), // ConflictEntityType, lib/operations/types.ts
    entityId: text("entity_id").notNull(),
    field: text("field").notNull(),
    valueA: text("value_a").notNull(),
    sourceA: text("source_a").notNull(),
    valueB: text("value_b").notNull(),
    sourceB: text("source_b").notNull(),
    status: text("status").notNull().default("open"), // "open" | "resolved"
    resolution: text("resolution"), // "kept_a" | "kept_b" | "dismissed"
    detectedAt: timestamp("detected_at", { withTimezone: true, mode: "date" }).notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [
    // One open conflict per contested field, not one per sync run: a nightly
    // sync would otherwise pile up an identical row every night until someone
    // resolved it, burying the other findings.
    uniqueIndex("operations_conflicts_entity_field_uq").on(table.organizationId, table.entityType, table.entityId, table.field),
    index("operations_conflicts_org_status_idx").on(table.organizationId, table.status),
  ],
);

/* ══ Agent runtime: durable task execution ══════════════════════════════════
 *
 * Before these tables, an agent run lived entirely in one HTTP request's
 * memory (lib/ask-aval/loop.ts): a worker restart mid-analysis lost the run
 * with no record it had started. These three tables are the durable half —
 * the task, its steps, and the approvals a step is waiting on.
 *
 * Storage discipline matches answer_audit_log: **digests, not payloads.** A
 * tool result can hold resident names and balances; a step table full of
 * those would be a second copy of the most sensitive data in the system,
 * retained for bookkeeping. Steps store a SHA-256 of the arguments and the
 * result plus non-identifying facts, which is enough to prove what happened
 * and to detect a replay, without the log becoming a liability of its own.
 */

// One agent run. `status` is the state machine from §13 of the production
// readiness guide; `leaseOwner`/`leaseExpiresAt` are the distributed lock that
// stops two workers executing the same task (§14).
export const agentTasks = pgTable(
  "agent_tasks",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    // The user whose authority the run carries. Every policy check re-reads
    // this rather than trusting anything in the task's own message history.
    userId: text("user_id").notNull(),
    // Persona id — a built-in role or a custom persona row. Resolved to a
    // permission envelope by lib/agents/permissions.ts on every step.
    agentId: text("agent_id").notNull(),
    goal: text("goal").notNull(),
    // QUEUED | RUNNING | WAITING_FOR_TOOL | WAITING_FOR_APPROVAL | COMPLETED | FAILED | CANCELLED
    status: text("status").notNull(),
    // Conversation state, so a resumed run continues rather than restarting.
    // Sized by maxSteps and the model's own max_tokens, not unbounded.
    executionScopeJson: jsonb("execution_scope_json").notNull().default({}),
    checkJson: jsonb("check_json").notNull().default({}),
    deadlineAt: timestamp("deadline_at", { withTimezone: true, mode: "date" }),
    transcriptJson: jsonb("transcript_json").notNull().default([]),
    stepCount: integer("step_count").notNull().default(0),
    maxSteps: integer("max_steps").notNull(),
    tokensUsed: integer("tokens_used").notNull().default(0),
    maxTokens: bigint("max_tokens", { mode: "number" }).notNull(),
    // Task-level retry bookkeeping. A model/provider outage is retried by a
    // later worker invocation with exponential backoff; it is not converted
    // immediately into a terminal failure and it is never retried in-memory.
    executionAttempts: integer("execution_attempts").notNull().default(0),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true, mode: "date" }),
    // Delegation lineage (§19). Depth is capped in lib/agents/policy.ts.
    parentTaskId: text("parent_task_id"),
    delegationDepth: integer("delegation_depth").notNull().default(0),
    // Cooperative cancellation: set by a request, observed by the worker at
    // the top of each step. A running step is never killed mid-flight, so a
    // cancelled task can never leave a half-executed mutating tool behind.
    cancelRequested: boolean("cancel_requested").notNull().default(false),
    // Worker lease. A task is claimable when its lease is absent or expired,
    // which is what makes crash recovery automatic: a dead worker's lease
    // simply times out and the next worker picks the task up mid-run.
    leaseOwner: text("lease_owner"),
    leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true, mode: "date" }),
    lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true, mode: "date" }),
    // Terminal outcome. `resultJson` is the rendered answer, the one payload
    // worth retaining because the user asked for it; `error` is a message,
    // never a stack trace or a provider response body.
    resultJson: jsonb("result_json"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
    finishedAt: timestamp("finished_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [
    index("agent_tasks_org_created_idx").on(table.organizationId, table.createdAt),
    // The claim query: find runnable work whose lease has expired.
    index("agent_tasks_status_lease_idx").on(table.status, table.leaseExpiresAt),
    index("agent_tasks_status_attempt_idx").on(table.status, table.nextAttemptAt),
    index("agent_tasks_parent_idx").on(table.parentTaskId),
  ],
);

// One row per executed step, appended as the run proceeds — this is what makes
// a run resumable and what the execution-trace UI reads.
export const agentTaskSteps = pgTable(
  "agent_task_steps",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id").notNull().references(() => agentTasks.id),
    organizationId: text("organization_id").notNull(),
    // Position of this row in the task's trace. Unique with taskId, so the
    // trace has one definite order and a racing writer loses loudly instead of
    // interleaving. Assigned by appendStep under the task's lease.
    sequence: integer("sequence").notNull(),
    // Which reasoning step this row belongs to. Deliberately NOT unique: one
    // step is a model call plus every tool call it proposed, so a step maps to
    // several rows. Duplicate *execution* is prevented by idempotencyKey
    // below, which is the guarantee that actually matters.
    stepIndex: integer("step_index").notNull(),
    // model_call | tool_call | policy_deny | approval_requested | approval_decided | delegation | error | completion
    kind: text("kind").notNull(),
    // The concrete route used for a model_call. Explicit history matters when
    // an org changes providers after a task has already run.
    modelProvider: text("model_provider"),
    modelName: text("model_name"),
    toolName: text("tool_name"),
    // allow | deny | require_approval — the policy engine's verdict, recorded
    // whether or not the tool then ran.
    policyEffect: text("policy_effect"),
    denyCode: text("deny_code"),
    riskLevel: text("risk_level"),
    // SHA-256 of the arguments and of the result. Never the values themselves.
    argsDigest: text("args_digest"),
    resultDigest: text("result_digest"),
    // Which attempt this was, so a retry is visible as a retry rather than as
    // two independent calls.
    attempt: integer("attempt").notNull().default(1),
    durationMs: integer("duration_ms"),
    // Present only for mutating tools. Unique across the table: a second
    // insert with the same key is rejected by the database, which is what
    // makes duplicate execution impossible rather than merely unlikely.
    idempotencyKey: text("idempotency_key"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("agent_task_steps_task_sequence_uq").on(table.taskId, table.sequence),
    // Nullable and unique: SQLite lets NULLs coexist, so read-only steps are
    // unconstrained while any two mutating steps sharing a key collide. This
    // index *is* the duplicate-prevention mechanism — a retried worker that
    // recomputes the same key cannot insert a second row, so the second
    // execution never happens rather than merely being unlikely.
    uniqueIndex("agent_task_steps_idempotency_uq").on(table.idempotencyKey),
    index("agent_task_steps_task_idx").on(table.taskId, table.stepIndex),
  ],
);

// A proposed action parked in WAITING_FOR_APPROVAL. The agent prepares it; a
// person decides. Rows are never deleted — a rejection is as much a record as
// an approval, and §15 wants both.
export const agentApprovals = pgTable(
  "agent_approvals",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id").notNull().references(() => agentTasks.id),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    stepIndex: integer("step_index").notNull(),
    toolName: text("tool_name").notNull(),
    riskLevel: text("risk_level").notNull(),
    // automatic | single_approver | elevated_approver | refused (lib/agents/financial.ts)
    tier: text("tier").notNull(),
    amountCents: bigint("amount_cents", { mode: "number" }),
    currency: text("currency"),
    // What the approver is shown: the action, its arguments in a redacted
    // summary form, and the evidence the agent assembled. Retained because a
    // person has to be able to see what they approved, later.
    evidenceJson: jsonb("evidence_json").notNull().default({}),
    // pending | approved | rejected | expired
    status: text("status").notNull(),
    requestedAt: timestamp("requested_at", { withTimezone: true, mode: "date" }).notNull(),
    // Approvals go stale: an amount that was right this morning may not be
    // tonight, so an undecided request expires rather than waiting forever.
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    decidedAt: timestamp("decided_at", { withTimezone: true, mode: "date" }),
    decidedByUserId: text("decided_by_user_id"),
    decisionNote: text("decision_note"),
    // Elevated financial actions need two distinct approvers. Decisions are
    // append-only rows below; these counters are only the query-friendly
    // projection used to decide whether the parked task may resume.
    requiredApprovals: integer("required_approvals").notNull().default(1),
    approvalsReceived: integer("approvals_received").notNull().default(0),
    policyVersion: integer("policy_version").notNull().default(1),
  },
  (table) => [
    index("agent_approvals_org_status_idx").on(table.organizationId, table.status),
    uniqueIndex("agent_approvals_task_step_uq").on(table.taskId, table.stepIndex),
  ],
);

// One immutable row per human decision. A unique (approval, user) pair means
// two clicks by the same person can never satisfy a two-person gate.
export const agentApprovalDecisions = pgTable(
  "agent_approval_decisions",
  {
    id: text("id").primaryKey(),
    approvalId: text("approval_id").notNull().references(() => agentApprovals.id),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    userId: text("user_id").notNull(),
    decision: text("decision").notNull(), // approved | rejected
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("agent_approval_decisions_approval_user_uq").on(table.approvalId, table.userId),
    index("agent_approval_decisions_org_created_idx").on(table.organizationId, table.createdAt),
  ],
);

// A financial policy is unusable until the workspace owner explicitly
// approves it. Automatic payment authority is intentionally absent: every
// money-moving action always requires at least one human decision.
export const agentExecutionPolicies = pgTable("agent_execution_policies", {
  organizationId: text("organization_id").primaryKey().references(() => organizations.id),
  status: text("status").notNull().default("draft"), // draft | approved | suspended
  singleApprovalMaxCents: bigint("single_approval_max_cents", { mode: "number" }).notNull().default(50_000),
  hardCeilingCents: bigint("hard_ceiling_cents", { mode: "number" }).notNull().default(2_500_000),
  dailyLimitCents: bigint("daily_limit_cents", { mode: "number" }).notNull().default(5_000_000),
  allowedCurrenciesJson: jsonb("allowed_currencies_json").notNull().default(["USD"]),
  // SHA-256 fingerprints only. Account identifiers remain in the provider;
  // Aval can check an allowlist without becoming another copy of bank data.
  allowedAccountFingerprintsJson: jsonb("allowed_account_fingerprints_json").notNull().default([]),
  version: integer("version").notNull().default(1),
  approvedByUserId: text("approved_by_user_id"),
  approvedAt: timestamp("approved_at", { withTimezone: true, mode: "date" }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
});

// Mutable reconciliation projection for each financial side effect. The
// adjacent event table is the immutable record; this row makes due-work and
// discrepancy queries bounded and indexable.
export const agentFinancialOperations = pgTable(
  "agent_financial_operations",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    taskId: text("task_id").notNull().references(() => agentTasks.id),
    approvalId: text("approval_id").references(() => agentApprovals.id),
    stepIndex: integer("step_index").notNull(),
    toolName: text("tool_name").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: text("currency").notNull(),
    accountFingerprint: text("account_fingerprint").notNull(),
    status: text("status").notNull(), // reserved | submitted | settled | failed | unknown | reversed
    reconciliationStatus: text("reconciliation_status").notNull().default("pending"),
    externalTransactionId: text("external_transaction_id"),
    resultDigest: text("result_digest"),
    discrepancyCode: text("discrepancy_code"),
    reconcileAttempts: integer("reconcile_attempts").notNull().default(0),
    nextReconcileAt: timestamp("next_reconcile_at", { withTimezone: true, mode: "date" }).notNull(),
    lastReconciledAt: timestamp("last_reconciled_at", { withTimezone: true, mode: "date" }),
    // Separate from the task lease: provider read-backs can overlap a task's
    // own worker, and two cron invocations must never reconcile one operation
    // concurrently. Expiry makes a dead reconciler recoverable.
    reconcileLeaseOwner: text("reconcile_lease_owner"),
    reconcileLeaseExpiresAt: timestamp("reconcile_lease_expires_at", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
    settledAt: timestamp("settled_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [
    uniqueIndex("agent_financial_operations_idempotency_uq").on(table.idempotencyKey),
    uniqueIndex("agent_financial_operations_external_uq").on(table.toolName, table.externalTransactionId),
    index("agent_financial_operations_reconcile_idx").on(table.reconciliationStatus, table.nextReconcileAt, table.reconcileLeaseExpiresAt),
    index("agent_financial_operations_org_created_idx").on(table.organizationId, table.createdAt),
  ],
);

export const agentFinancialEvents = pgTable(
  "agent_financial_events",
  {
    id: text("id").primaryKey(),
    operationId: text("operation_id").notNull().references(() => agentFinancialOperations.id),
    organizationId: text("organization_id").notNull().references(() => organizations.id),
    sequence: integer("sequence").notNull(),
    kind: text("kind").notNull(),
    payloadDigest: text("payload_digest").notNull(),
    externalTransactionId: text("external_transaction_id"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (table) => [
    uniqueIndex("agent_financial_events_operation_sequence_uq").on(table.operationId, table.sequence),
    index("agent_financial_events_org_created_idx").on(table.organizationId, table.createdAt),
  ],
);

// Persistent worker telemetry backs the health endpoint and survives log
// retention. It contains counts and timings only, never goals or tool data.
export const agentWorkerRuns = pgTable(
  "agent_worker_runs",
  {
    id: text("id").primaryKey(),
    trigger: text("trigger").notNull(), // scheduled | request | approval | manual
    status: text("status").notNull(), // running | completed | failed
    tasksScanned: integer("tasks_scanned").notNull().default(0),
    tasksAdvanced: integer("tasks_advanced").notNull().default(0),
    tasksCompleted: integer("tasks_completed").notNull().default(0),
    tasksFailed: integer("tasks_failed").notNull().default(0),
    tasksParked: integer("tasks_parked").notNull().default(0),
    errorDigest: text("error_digest"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }).notNull(),
    finishedAt: timestamp("finished_at", { withTimezone: true, mode: "date" }),
  },
  (table) => [index("agent_worker_runs_started_idx").on(table.startedAt)],
);

// Native workspace planning. Dates are UTC instants; UI uses the viewer's time zone.
export const planningProjects = pgTable("planning_projects", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(()=>organizations.id),
  title: text("title").notNull(), description: text("description").notNull().default(""), color: text("color").notNull().default("blue"), createdAt: integer("created_at").notNull(),
}, (t)=>[index("planning_projects_org_idx").on(t.organizationId)]);
export const planningItems = pgTable("planning_items", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(()=>organizations.id),
  title: text("title").notNull(), description: text("description").notNull().default(""), kind: text("kind").notNull().default("task"), status: text("status").notNull().default("planned"),
  projectId: text("project_id").references(()=>planningProjects.id), assigneeId: text("assignee_id"), startsAt: integer("starts_at").notNull(), endsAt: integer("ends_at").notNull(),
  version: integer("version").notNull().default(1), createdBy: text("created_by").notNull(), updatedAt: integer("updated_at").notNull(),
}, (t)=>[index("planning_items_org_date_idx").on(t.organizationId,t.startsAt)]);

// One record per authenticated active minute; uniqueness prevents double counting across tabs.
export const workspaceUsage = pgTable("workspace_usage", {
  id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id),
  userId: text("user_id").notNull(), minute: integer("minute").notNull(),
}, t => [uniqueIndex("workspace_usage_subject_minute").on(t.organizationId, t.userId, t.minute)]);

/** Durable provider operations: reserve before sending; uncertain outcomes are never blindly retried. */
export const communicationDeliveries = pgTable("communication_deliveries", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  connectionId: text("connection_id").notNull().references(() => integrationConnections.id),
  requestKey: text("request_key").notNull(),
  payloadDigest: text("payload_digest").notNull(),
  kind: text("kind").notNull(),
  destination: text("destination").notNull(),
  body: text("body").notNull(),
  status: text("status").notNull().default("sending"),
  providerId: text("provider_id"),
  error: text("error"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
}, (t) => [uniqueIndex("communication_deliveries_org_request_uq").on(t.organizationId, t.requestKey), index("communication_deliveries_org_created_idx").on(t.organizationId, t.createdAt)]);

export const communicationSettings = pgTable("communication_settings", {
  organizationId: text("organization_id").primaryKey().references(() => organizations.id),
  configJson: jsonb("config_json").notNull().default({}),
  updatedBy: text("updated_by").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull(),
});

export const communicationPollSources = pgTable('communication_poll_sources', {
 id: text('id').primaryKey(),
 organizationId: text('organization_id').notNull().references(()=>organizations.id),
 provider: text('provider').notNull(),
 resourceId: text('resource_id').notNull().default(''),
 enabled: boolean('enabled').notNull().default(true),
 lastAttemptAt: timestamp('last_attempt_at', { withTimezone: true, mode: "date" }),
 lastSuccessAt: timestamp('last_success_at', { withTimezone: true, mode: "date" }),
 error: text('error'),
}, t=>[uniqueIndex('communication_poll_source_uq').on(t.organizationId,t.provider,t.resourceId),index('communication_poll_due_idx').on(t.enabled,t.lastAttemptAt)]);


export const agentChecks = pgTable("agent_checks", {
 id:text("id").primaryKey(), organizationId:text("organization_id").notNull().references(()=>organizations.id), taskId:text("task_id").notNull().references(()=>agentTasks.id), stepIndex:integer("step_index").notNull(), exitCode:integer("exit_code").notNull(), outputJson:jsonb("output_json").notNull(), createdAt:timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
},t=>[index("agent_checks_task_idx").on(t.organizationId,t.taskId)]);
export const agentMemory = pgTable("agent_memory", {
 id:text("id").primaryKey(),organizationId:text("organization_id").notNull().references(()=>organizations.id),taskId:text("task_id").notNull().references(()=>agentTasks.id),stepIndex:integer("step_index").notNull(),requestKey:text("request_key").notNull(),body:text("body").notNull(),createdAt:timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
},t=>[uniqueIndex("agent_memory_request_uq").on(t.organizationId,t.requestKey),index("agent_memory_task_step_idx").on(t.taskId,t.stepIndex)]);
export const agentPlanNodes = pgTable("agent_plan_nodes", {
 id:text("id").primaryKey(),organizationId:text("organization_id").notNull().references(()=>organizations.id),rootTaskId:text("root_task_id").notNull().references(()=>agentTasks.id),revision:integer("revision").notNull(),nodeKey:text("node_key").notNull(),taskId:text("task_id").notNull().references(()=>agentTasks.id),dependenciesJson:jsonb("dependencies_json").notNull(),createdAt:timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
},t=>[uniqueIndex("agent_plan_node_uq").on(t.rootTaskId,t.revision,t.nodeKey),index("agent_plan_root_idx").on(t.rootTaskId,t.revision)]);

export const agentModelContexts = pgTable("agent_model_contexts", {
 id:text("id").primaryKey(),organizationId:text("organization_id").notNull().references(()=>organizations.id),taskId:text("task_id").notNull().references(()=>agentTasks.id),stepIndex:integer("step_index").notNull(),contextJson:jsonb("context_json").notNull(),digest:text("digest").notNull(),createdAt:timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(),
},t=>[index("agent_model_context_task_idx").on(t.organizationId,t.taskId,t.stepIndex)]);
