import type { IntegrationProvider } from "./catalog";

export type AdditionalProviderId = "yardi_breeze" | "reapit" | "sme_professional" | "10ninety" | "arthur" | "joblogic" | "rentvine" | "asana" | "buildingstack" | "gohighlevel" | "igloohome" | "peach" | "propstack" | "resharmonics" | "realpad" | "rentvision" | "rm_cloud" | "showmojo" | "tenantcloud" | "street" | "yardi_kube" | "google_chat" | "microsoft_teams" | "imessage" | "google_drive" | "google_sheets" | "onedrive" | "box" | "rightmove" | "zoopla" | "onthemarket" | "meta";

function partner(id: AdditionalProviderId, title: string, documentationUrl: string, setupBlocker: string, category: IntegrationProvider["category"] = "Leasing & PMS"): IntegrationProvider {
  return { id, title, category, description: `Connect ${title} to your Aval workspace once the provider adapter is approved.`, authMode: "credentials", permissions: [], credentialFields: [], env: [], webhook: false, readOnly: true, note: setupBlocker, setupBlocker, documentationUrl };
}
function key(id: AdditionalProviderId, title: string, documentationUrl: string, credentialFields: NonNullable<IntegrationProvider["credentialFields"]>, note: string): IntegrationProvider {
  return { id, title, category: "Leasing & PMS", description: `Connect your ${title} account and verify API access.`, authMode: "credentials", permissions: ["Read connected account records"], credentialFields, env: [], webhook: false, readOnly: true, note, documentationUrl };
}
function oauth(id: AdditionalProviderId, title: string, category: IntegrationProvider["category"], env: string[], permissions: string[], documentationUrl: string, note: string): IntegrationProvider {
  return { id, title, category, description: `Connect your ${title} account with read permissions.`, authMode: "oauth2", permissions, env, webhook: false, readOnly: true, note, documentationUrl };
}
export const additionalProviders: IntegrationProvider[] = [
  partner("yardi_breeze", "Yardi Breeze", "https://www.yardibreeze.com/", "Breeze requires a product-specific agreement and interface specification. A Voyager key does not establish Breeze access."),
  partner("sme_professional", "SME Professional", "https://smeprofessional.co.uk/", "Provider API specification, authentication contract, and a test account are required before this adapter can be implemented."),
  partner("10ninety", "10ninety", "https://www.10ninety.co.uk/", "Request an approved integration contract and sandbox from 10ninety; no verified public API contract is available in Aval yet."),
  partner("joblogic", "Joblogic", "https://support.joblogic.com/docs/api-access", "Enable Joblogic API Access and obtain the regional API specification and sandbox to finish the adapter."),
  partner("buildingstack", "BuildingStack", "https://www.buildingstack.com/landlord-property-management-software/integrations/", "Building Stack offers customized APIs through its sales team. The account-specific API contract is required to implement this adapter."),
  partner("igloohome", "Igloohome", "https://www.igloohome.co/developers", "Choose the igloohome or iglooworks API product and obtain a sandbox. Access-device operations need a separate permission and device mapping review."),
  partner("peach", "Peach Software", "", "Confirm the exact Peach Software vendor and API product. The screenshot alone does not identify an unambiguous property-management API."),
  partner("resharmonics", "Res:Harmonics", "https://apidocs.resharmonics.com/", "Request the v3 client ID, secret, base URL and auth URL from Res:Harmonics. Tenant-specific OAuth configuration and field mapping remain required."),
  partner("realpad", "Realpad", "https://dev.realpadsoftware.com/", "Select the Realpad export/API product and obtain tenant credentials and sample responses to implement its XML/data takeout mapping."),
  partner("rentvision", "RentVision", "https://www.rentvision.com/", "Provider-approved API access and a documented data contract are required; Aval has no verified public read API contract yet."),
  partner("rm_cloud", "RM Cloud", "", "Confirm the RM Cloud vendor and product URL. Multiple unrelated systems share this name; do not use Rent Manager credentials here."),
  partner("showmojo", "ShowMojo", "https://hello.showmojo.com/integration/", "Confirm the current OAuth/listing API contract with ShowMojo. The older Basic-auth listing-import PDF is not sufficient for a read/sync adapter."),
  partner("tenantcloud", "TenantCloud", "https://www.tenantcloud.com/", "Partner API access, current documentation and a sandbox are required to finish the TenantCloud adapter."),
  partner("yardi_kube", "Yardi Kube", "https://www.yardikube.com/", "Obtain the Kube-specific integration agreement and API contract. Voyager and Breeze credentials are not interchangeable with Kube."),
  partner("imessage", "iMessage", "https://register.apple.com/messages", "Consumer iMessage has no supported general-purpose server API. Use the separate Apple Messages for Business connection with an approved messaging service provider.", "Communication"),
  partner("rightmove", "Rightmove", "https://www.rightmove.co.uk/adf.html", "Rightmove requires an approved datafeed provider, branch identifiers and feed certification. Listing publication is a separate write workflow, not a general listing-read API.", "Marketing"),
  partner("zoopla", "Zoopla", "https://support.zoopla.co.uk/hc/en-gb/sections/360004580137-API-s", "Request the current member/provider API contract and branch access from Zoopla. Do not assume its legacy public API supports listing publication.", "Marketing"),
  partner("onthemarket", "OnTheMarket", "https://expert.onthemarket.com/", "Obtain an approved datafeed agreement, branch configuration and validation examples from OnTheMarket before implementing publication.", "Marketing"),
  key("rentvine", "Rentvine", "https://docs.rentvine.com/", [{ key: "subdomain", label: "Rentvine account subdomain" }, { key: "accessKey", label: "Access key", secret: true }, { key: "secret", label: "Secret", secret: true }], "Uses Rentvine Basic authentication, scoped to your account subdomain, to read properties."),
  key("propstack", "PropStack", "https://docs.propstack.de/", [{ key: "apiKey", label: "Propstack API key", secret: true }], "Uses X-API-KEY authentication on Propstack's documented v1 API to read units."),
  key("street", "Street", "https://developers.street.co.uk/docs/street-open-api/", [{ key: "apiKey", label: "Street Open API token", secret: true }], "Uses a Street Open API bearer token to read properties. Request a sandbox from Street for launch validation."),
  key("asana", "Asana", "https://developers.asana.com/docs/personal-access-token", [{ key: "apiKey", label: "Asana personal access token", secret: true }], "Verifies the authenticated Asana user. Project import is not available yet. Aval only issues read requests."),
  key("gohighlevel", "GoHighLevel", "https://marketplace.gohighlevel.com/docs/", [{ key: "apiKey", label: "Private integration token", secret: true }, { key: "locationId", label: "Location ID" }], "Verifies the selected location with a scoped private integration token and locations.readonly. Contact import is not available yet. Legacy v1 API keys are not supported."),
  oauth("reapit", "Reapit", "Leasing & PMS", ["REAPIT_CLIENT_ID", "REAPIT_CLIENT_SECRET"], [], "https://foundations-documentation.reapit.cloud/api/reapit-connect", "Reapit Connect OAuth with app-registered permissions. The customer must install Aval through Reapit Foundations."),
  oauth("arthur", "Arthur Online", "Leasing & PMS", ["ARTHUR_CLIENT_ID", "ARTHUR_CLIENT_SECRET"], [], "https://developer.arthuronline.co.uk/", "Arthur OAuth. Verify the authorized entity before reading properties."),
  oauth("google_chat", "Google Chat", "Communication", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"], ["https://www.googleapis.com/auth/chat.spaces.readonly", "https://www.googleapis.com/auth/chat.messages.readonly"], "https://developers.google.com/workspace/chat/authenticate-authorize", "User-authorized read access to Chat spaces and messages; enable the Chat API. Sending is not requested by this connection."),
  oauth("microsoft_teams", "Microsoft Teams", "Communication", ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"], ["offline_access", "User.Read", "Chat.Read"], "https://learn.microsoft.com/en-us/graph/api/chat-list-messages", "Delegated read access to the user's Teams chats. Tenant policy may require administrator consent. Channels and sending are separate permissions."),
  oauth("google_drive", "Google Drive", "Knowledge", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"], ["https://www.googleapis.com/auth/drive.metadata.readonly"], "https://developers.google.com/workspace/drive/api/reference/rest/v3/files/list", "Verifies file-metadata access. File-content access is not requested, and automatic file import is not available yet."),
  oauth("google_sheets", "Google Sheets", "Knowledge", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"], ["https://www.googleapis.com/auth/drive.metadata.readonly", "https://www.googleapis.com/auth/spreadsheets.readonly"], "https://developers.google.com/workspace/sheets/api/reference/rest/v4/spreadsheets/get", "Verifies spreadsheet discovery access. Spreadsheet-content import and accounting normalization are not available yet."),
  oauth("onedrive", "OneDrive / SharePoint", "Knowledge", ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET"], ["offline_access", "User.Read", "Files.Read.All"], "https://learn.microsoft.com/en-us/graph/api/driveitem-list-children", "Verifies delegated access to the signed-in user’s default drive. File import and shared-library selection are not available yet."),
  oauth("box", "Box", "Knowledge", ["BOX_CLIENT_ID", "BOX_CLIENT_SECRET"], [], "https://developer.box.com/guides/authentication/oauth2/", "OAuth consent plus application-configured read permissions. Verification checks the root folder. File import is not available yet."),
  { ...key("meta", "Meta", "https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving", [{ key: "accessToken", label: "Page access token", secret: true }, { key: "pageId", label: "Facebook Page ID" }], "Reads lead forms for the authorized Page. Requires Meta app review and Page access; WhatsApp uses its own separate connection."), category: "Marketing", env: ["META_GRAPH_API_VERSION"], permissions: ["pages_read_engagement", "leads_retrieval", "pages_show_list"] },
];
