-- GENERATED by scripts/migration/generate-rls.mjs.
-- Request identity is supplied with transaction-local set_config calls.

CREATE SCHEMA IF NOT EXISTS aval_private;
REVOKE ALL ON SCHEMA aval_private FROM PUBLIC;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aval_app') THEN
    CREATE ROLE aval_app NOLOGIN NOINHERIT NOBYPASSRLS;
  END IF;
END $$;
GRANT aval_app TO postgres;
GRANT USAGE ON SCHEMA public TO aval_app;

CREATE OR REPLACE FUNCTION aval_private.current_principal_id() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('aval.principal_id', true), '')
$$;

CREATE OR REPLACE FUNCTION aval_private.current_organization_id() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('aval.organization_id', true), '')
$$;

CREATE OR REPLACE FUNCTION aval_private.has_org_access(target_org text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id()
    AND EXISTS (
      SELECT 1 FROM public.access_grants grant_row
      JOIN public.principals principal ON principal.id = grant_row.principal_id AND principal.status = 'active'
      WHERE grant_row.organization_id = target_org
        AND grant_row.principal_id = aval_private.current_principal_id()
        AND grant_row.revoked_at IS NULL
        AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
    )
$$;

CREATE OR REPLACE FUNCTION aval_private.has_org_role(target_org text, allowed_roles text[]) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id()
    AND EXISTS (
      SELECT 1 FROM public.access_grants grant_row
      JOIN public.principals principal ON principal.id = grant_row.principal_id AND principal.status = 'active'
      WHERE grant_row.organization_id = target_org
        AND grant_row.principal_id = aval_private.current_principal_id()
        AND grant_row.role = ANY(allowed_roles)
        AND grant_row.organization_scope
        AND grant_row.revoked_at IS NULL
        AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
    )
$$;

CREATE OR REPLACE FUNCTION aval_private.can_access_property(target_org text, target_property text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id() AND EXISTS (
    SELECT 1 FROM public.properties property_row
    JOIN public.access_grants grant_row ON grant_row.organization_id = property_row.organization_id
      AND grant_row.principal_id = aval_private.current_principal_id()
      AND grant_row.revoked_at IS NULL
      AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
      AND (
        grant_row.organization_scope
        OR grant_row.property_id = property_row.id
        OR grant_row.ownership_entity_id = property_row.ownership_entity_id
        OR grant_row.portfolio_id = property_row.portfolio_id
        OR grant_row.region_id = property_row.region_id
      )
    WHERE property_row.organization_id = target_org AND property_row.id = target_property
  )
$$;

CREATE OR REPLACE FUNCTION aval_private.can_manage_property(target_org text, target_property text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT target_org = aval_private.current_organization_id() AND EXISTS (
    SELECT 1 FROM public.properties property_row
    JOIN public.access_grants grant_row ON grant_row.organization_id = property_row.organization_id
      AND grant_row.principal_id = aval_private.current_principal_id()
      AND grant_row.role = ANY(ARRAY['org_admin','regional_manager','property_manager','operator'])
      AND grant_row.revoked_at IS NULL
      AND (grant_row.expires_at IS NULL OR grant_row.expires_at > statement_timestamp())
      AND (
        grant_row.organization_scope
        OR grant_row.property_id = property_row.id
        OR grant_row.ownership_entity_id = property_row.ownership_entity_id
        OR grant_row.portfolio_id = property_row.portfolio_id
        OR grant_row.region_id = property_row.region_id
      )
    WHERE property_row.organization_id = target_org AND property_row.id = target_property
  )
$$;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO aval_app;


ALTER TABLE public."access_grants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."access_grants" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "access_grants_select" ON public."access_grants";
CREATE POLICY "access_grants_select" ON public."access_grants"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "access_grants_insert" ON public."access_grants";
CREATE POLICY "access_grants_insert" ON public."access_grants"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "access_grants_update" ON public."access_grants";
CREATE POLICY "access_grants_update" ON public."access_grants"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "access_grants_delete" ON public."access_grants";
CREATE POLICY "access_grants_delete" ON public."access_grants"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

ALTER TABLE public."agent_approval_decisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_approval_decisions" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_approval_decisions_select" ON public."agent_approval_decisions";
CREATE POLICY "agent_approval_decisions_select" ON public."agent_approval_decisions"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_approval_decisions_insert" ON public."agent_approval_decisions";
CREATE POLICY "agent_approval_decisions_insert" ON public."agent_approval_decisions"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_approval_decisions_update" ON public."agent_approval_decisions";
CREATE POLICY "agent_approval_decisions_update" ON public."agent_approval_decisions"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_approval_decisions_delete" ON public."agent_approval_decisions";
CREATE POLICY "agent_approval_decisions_delete" ON public."agent_approval_decisions"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_approvals" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_approvals_select" ON public."agent_approvals";
CREATE POLICY "agent_approvals_select" ON public."agent_approvals"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_approvals_insert" ON public."agent_approvals";
CREATE POLICY "agent_approvals_insert" ON public."agent_approvals"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_approvals_update" ON public."agent_approvals";
CREATE POLICY "agent_approvals_update" ON public."agent_approvals"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_approvals_delete" ON public."agent_approvals";
CREATE POLICY "agent_approvals_delete" ON public."agent_approvals"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_checks" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_checks_select" ON public."agent_checks";
CREATE POLICY "agent_checks_select" ON public."agent_checks"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_checks_insert" ON public."agent_checks";
CREATE POLICY "agent_checks_insert" ON public."agent_checks"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_checks_update" ON public."agent_checks";
CREATE POLICY "agent_checks_update" ON public."agent_checks"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_checks_delete" ON public."agent_checks";
CREATE POLICY "agent_checks_delete" ON public."agent_checks"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_execution_policies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_execution_policies" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_execution_policies_select" ON public."agent_execution_policies";
CREATE POLICY "agent_execution_policies_select" ON public."agent_execution_policies"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_execution_policies_insert" ON public."agent_execution_policies";
CREATE POLICY "agent_execution_policies_insert" ON public."agent_execution_policies"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_execution_policies_update" ON public."agent_execution_policies";
CREATE POLICY "agent_execution_policies_update" ON public."agent_execution_policies"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_execution_policies_delete" ON public."agent_execution_policies";
CREATE POLICY "agent_execution_policies_delete" ON public."agent_execution_policies"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_financial_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_financial_events" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_financial_events_select" ON public."agent_financial_events";
CREATE POLICY "agent_financial_events_select" ON public."agent_financial_events"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_financial_events_insert" ON public."agent_financial_events";
CREATE POLICY "agent_financial_events_insert" ON public."agent_financial_events"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_financial_events_update" ON public."agent_financial_events";
CREATE POLICY "agent_financial_events_update" ON public."agent_financial_events"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_financial_events_delete" ON public."agent_financial_events";
CREATE POLICY "agent_financial_events_delete" ON public."agent_financial_events"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_financial_operations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_financial_operations" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_financial_operations_select" ON public."agent_financial_operations";
CREATE POLICY "agent_financial_operations_select" ON public."agent_financial_operations"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_financial_operations_insert" ON public."agent_financial_operations";
CREATE POLICY "agent_financial_operations_insert" ON public."agent_financial_operations"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_financial_operations_update" ON public."agent_financial_operations";
CREATE POLICY "agent_financial_operations_update" ON public."agent_financial_operations"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_financial_operations_delete" ON public."agent_financial_operations";
CREATE POLICY "agent_financial_operations_delete" ON public."agent_financial_operations"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_memory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_memory" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_memory_select" ON public."agent_memory";
CREATE POLICY "agent_memory_select" ON public."agent_memory"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_memory_insert" ON public."agent_memory";
CREATE POLICY "agent_memory_insert" ON public."agent_memory"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_memory_update" ON public."agent_memory";
CREATE POLICY "agent_memory_update" ON public."agent_memory"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_memory_delete" ON public."agent_memory";
CREATE POLICY "agent_memory_delete" ON public."agent_memory"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_model_contexts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_model_contexts" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_model_contexts_select" ON public."agent_model_contexts";
CREATE POLICY "agent_model_contexts_select" ON public."agent_model_contexts"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_model_contexts_insert" ON public."agent_model_contexts";
CREATE POLICY "agent_model_contexts_insert" ON public."agent_model_contexts"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_model_contexts_update" ON public."agent_model_contexts";
CREATE POLICY "agent_model_contexts_update" ON public."agent_model_contexts"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_model_contexts_delete" ON public."agent_model_contexts";
CREATE POLICY "agent_model_contexts_delete" ON public."agent_model_contexts"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_personas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_personas" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_personas_select" ON public."agent_personas";
CREATE POLICY "agent_personas_select" ON public."agent_personas"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_personas_insert" ON public."agent_personas";
CREATE POLICY "agent_personas_insert" ON public."agent_personas"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_personas_update" ON public."agent_personas";
CREATE POLICY "agent_personas_update" ON public."agent_personas"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_personas_delete" ON public."agent_personas";
CREATE POLICY "agent_personas_delete" ON public."agent_personas"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_plan_nodes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_plan_nodes" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_plan_nodes_select" ON public."agent_plan_nodes";
CREATE POLICY "agent_plan_nodes_select" ON public."agent_plan_nodes"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_plan_nodes_insert" ON public."agent_plan_nodes";
CREATE POLICY "agent_plan_nodes_insert" ON public."agent_plan_nodes"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_plan_nodes_update" ON public."agent_plan_nodes";
CREATE POLICY "agent_plan_nodes_update" ON public."agent_plan_nodes"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_plan_nodes_delete" ON public."agent_plan_nodes";
CREATE POLICY "agent_plan_nodes_delete" ON public."agent_plan_nodes"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_task_steps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_task_steps" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_task_steps_select" ON public."agent_task_steps";
CREATE POLICY "agent_task_steps_select" ON public."agent_task_steps"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_task_steps_insert" ON public."agent_task_steps";
CREATE POLICY "agent_task_steps_insert" ON public."agent_task_steps"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_task_steps_update" ON public."agent_task_steps";
CREATE POLICY "agent_task_steps_update" ON public."agent_task_steps"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_task_steps_delete" ON public."agent_task_steps";
CREATE POLICY "agent_task_steps_delete" ON public."agent_task_steps"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."agent_tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."agent_tasks" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_tasks_select" ON public."agent_tasks";
CREATE POLICY "agent_tasks_select" ON public."agent_tasks"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "agent_tasks_insert" ON public."agent_tasks";
CREATE POLICY "agent_tasks_insert" ON public."agent_tasks"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_tasks_update" ON public."agent_tasks";
CREATE POLICY "agent_tasks_update" ON public."agent_tasks"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "agent_tasks_delete" ON public."agent_tasks";
CREATE POLICY "agent_tasks_delete" ON public."agent_tasks"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."ai_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ai_usage" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ai_usage_select" ON public."ai_usage";
CREATE POLICY "ai_usage_select" ON public."ai_usage"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "ai_usage_insert" ON public."ai_usage";
CREATE POLICY "ai_usage_insert" ON public."ai_usage"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "ai_usage_update" ON public."ai_usage";
CREATE POLICY "ai_usage_update" ON public."ai_usage"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "ai_usage_delete" ON public."ai_usage";
CREATE POLICY "ai_usage_delete" ON public."ai_usage"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."answer_audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."answer_audit_log" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "answer_audit_log_select" ON public."answer_audit_log";
CREATE POLICY "answer_audit_log_select" ON public."answer_audit_log"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "answer_audit_log_insert" ON public."answer_audit_log";
CREATE POLICY "answer_audit_log_insert" ON public."answer_audit_log"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "answer_audit_log_update" ON public."answer_audit_log";
CREATE POLICY "answer_audit_log_update" ON public."answer_audit_log"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "answer_audit_log_delete" ON public."answer_audit_log";
CREATE POLICY "answer_audit_log_delete" ON public."answer_audit_log"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."approval_authorities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."approval_authorities" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "approval_authorities_select" ON public."approval_authorities";
CREATE POLICY "approval_authorities_select" ON public."approval_authorities"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "approval_authorities_insert" ON public."approval_authorities";
CREATE POLICY "approval_authorities_insert" ON public."approval_authorities"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "approval_authorities_update" ON public."approval_authorities";
CREATE POLICY "approval_authorities_update" ON public."approval_authorities"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "approval_authorities_delete" ON public."approval_authorities";
CREATE POLICY "approval_authorities_delete" ON public."approval_authorities"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

ALTER TABLE public."automation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."automation_runs" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "automation_runs_select" ON public."automation_runs";
CREATE POLICY "automation_runs_select" ON public."automation_runs"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "automation_runs_insert" ON public."automation_runs";
CREATE POLICY "automation_runs_insert" ON public."automation_runs"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "automation_runs_update" ON public."automation_runs";
CREATE POLICY "automation_runs_update" ON public."automation_runs"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "automation_runs_delete" ON public."automation_runs";
CREATE POLICY "automation_runs_delete" ON public."automation_runs"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."communication_deliveries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."communication_deliveries" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "communication_deliveries_select" ON public."communication_deliveries";
CREATE POLICY "communication_deliveries_select" ON public."communication_deliveries"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "communication_deliveries_insert" ON public."communication_deliveries";
CREATE POLICY "communication_deliveries_insert" ON public."communication_deliveries"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_deliveries_update" ON public."communication_deliveries";
CREATE POLICY "communication_deliveries_update" ON public."communication_deliveries"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_deliveries_delete" ON public."communication_deliveries";
CREATE POLICY "communication_deliveries_delete" ON public."communication_deliveries"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."communication_poll_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."communication_poll_sources" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "communication_poll_sources_select" ON public."communication_poll_sources";
CREATE POLICY "communication_poll_sources_select" ON public."communication_poll_sources"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "communication_poll_sources_insert" ON public."communication_poll_sources";
CREATE POLICY "communication_poll_sources_insert" ON public."communication_poll_sources"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_poll_sources_update" ON public."communication_poll_sources";
CREATE POLICY "communication_poll_sources_update" ON public."communication_poll_sources"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_poll_sources_delete" ON public."communication_poll_sources";
CREATE POLICY "communication_poll_sources_delete" ON public."communication_poll_sources"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."communication_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."communication_settings" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "communication_settings_select" ON public."communication_settings";
CREATE POLICY "communication_settings_select" ON public."communication_settings"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "communication_settings_insert" ON public."communication_settings";
CREATE POLICY "communication_settings_insert" ON public."communication_settings"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_settings_update" ON public."communication_settings";
CREATE POLICY "communication_settings_update" ON public."communication_settings"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "communication_settings_delete" ON public."communication_settings";
CREATE POLICY "communication_settings_delete" ON public."communication_settings"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."conversations" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "conversations_select" ON public."conversations";
CREATE POLICY "conversations_select" ON public."conversations"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "conversations_insert" ON public."conversations";
CREATE POLICY "conversations_insert" ON public."conversations"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "conversations_update" ON public."conversations";
CREATE POLICY "conversations_update" ON public."conversations"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "conversations_delete" ON public."conversations";
CREATE POLICY "conversations_delete" ON public."conversations"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."documents" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "documents_select" ON public."documents";
CREATE POLICY "documents_select" ON public."documents"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "documents_insert" ON public."documents";
CREATE POLICY "documents_insert" ON public."documents"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "documents_update" ON public."documents";
CREATE POLICY "documents_update" ON public."documents"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "documents_delete" ON public."documents";
CREATE POLICY "documents_delete" ON public."documents"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."draft_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."draft_documents" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "draft_documents_select" ON public."draft_documents";
CREATE POLICY "draft_documents_select" ON public."draft_documents"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "draft_documents_insert" ON public."draft_documents";
CREATE POLICY "draft_documents_insert" ON public."draft_documents"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "draft_documents_update" ON public."draft_documents";
CREATE POLICY "draft_documents_update" ON public."draft_documents"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "draft_documents_delete" ON public."draft_documents";
CREATE POLICY "draft_documents_delete" ON public."draft_documents"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."funnel_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."funnel_snapshots" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "funnel_snapshots_select" ON public."funnel_snapshots";
CREATE POLICY "funnel_snapshots_select" ON public."funnel_snapshots"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "funnel_snapshots_insert" ON public."funnel_snapshots";
CREATE POLICY "funnel_snapshots_insert" ON public."funnel_snapshots"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "funnel_snapshots_update" ON public."funnel_snapshots";
CREATE POLICY "funnel_snapshots_update" ON public."funnel_snapshots"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "funnel_snapshots_delete" ON public."funnel_snapshots";
CREATE POLICY "funnel_snapshots_delete" ON public."funnel_snapshots"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."gl_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."gl_accounts" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "gl_accounts_select" ON public."gl_accounts";
CREATE POLICY "gl_accounts_select" ON public."gl_accounts"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "gl_accounts_insert" ON public."gl_accounts";
CREATE POLICY "gl_accounts_insert" ON public."gl_accounts"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "gl_accounts_update" ON public."gl_accounts";
CREATE POLICY "gl_accounts_update" ON public."gl_accounts"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "gl_accounts_delete" ON public."gl_accounts";
CREATE POLICY "gl_accounts_delete" ON public."gl_accounts"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."gl_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."gl_transactions" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "gl_transactions_select" ON public."gl_transactions";
CREATE POLICY "gl_transactions_select" ON public."gl_transactions"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "gl_transactions_insert" ON public."gl_transactions";
CREATE POLICY "gl_transactions_insert" ON public."gl_transactions"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "gl_transactions_update" ON public."gl_transactions";
CREATE POLICY "gl_transactions_update" ON public."gl_transactions"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "gl_transactions_delete" ON public."gl_transactions";
CREATE POLICY "gl_transactions_delete" ON public."gl_transactions"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."insight_decisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."insight_decisions" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "insight_decisions_select" ON public."insight_decisions";
CREATE POLICY "insight_decisions_select" ON public."insight_decisions"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "insight_decisions_insert" ON public."insight_decisions";
CREATE POLICY "insight_decisions_insert" ON public."insight_decisions"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "insight_decisions_update" ON public."insight_decisions";
CREATE POLICY "insight_decisions_update" ON public."insight_decisions"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "insight_decisions_delete" ON public."insight_decisions";
CREATE POLICY "insight_decisions_delete" ON public."insight_decisions"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."integration_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."integration_connections" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "integration_connections_select" ON public."integration_connections";
CREATE POLICY "integration_connections_select" ON public."integration_connections"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "integration_connections_insert" ON public."integration_connections";
CREATE POLICY "integration_connections_insert" ON public."integration_connections"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_connections_update" ON public."integration_connections";
CREATE POLICY "integration_connections_update" ON public."integration_connections"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_connections_delete" ON public."integration_connections";
CREATE POLICY "integration_connections_delete" ON public."integration_connections"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."integration_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."integration_events" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "integration_events_select" ON public."integration_events";
CREATE POLICY "integration_events_select" ON public."integration_events"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "integration_events_insert" ON public."integration_events";
CREATE POLICY "integration_events_insert" ON public."integration_events"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_events_update" ON public."integration_events";
CREATE POLICY "integration_events_update" ON public."integration_events"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_events_delete" ON public."integration_events";
CREATE POLICY "integration_events_delete" ON public."integration_events"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."integration_sync_state" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."integration_sync_state" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "integration_sync_state_select" ON public."integration_sync_state";
CREATE POLICY "integration_sync_state_select" ON public."integration_sync_state"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "integration_sync_state_insert" ON public."integration_sync_state";
CREATE POLICY "integration_sync_state_insert" ON public."integration_sync_state"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_sync_state_update" ON public."integration_sync_state";
CREATE POLICY "integration_sync_state_update" ON public."integration_sync_state"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "integration_sync_state_delete" ON public."integration_sync_state";
CREATE POLICY "integration_sync_state_delete" ON public."integration_sync_state"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."learned_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."learned_preferences" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "learned_preferences_select" ON public."learned_preferences";
CREATE POLICY "learned_preferences_select" ON public."learned_preferences"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "learned_preferences_insert" ON public."learned_preferences";
CREATE POLICY "learned_preferences_insert" ON public."learned_preferences"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "learned_preferences_update" ON public."learned_preferences";
CREATE POLICY "learned_preferences_update" ON public."learned_preferences"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "learned_preferences_delete" ON public."learned_preferences";
CREATE POLICY "learned_preferences_delete" ON public."learned_preferences"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."lease_residents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lease_residents" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lease_residents_select" ON public."lease_residents";
CREATE POLICY "lease_residents_select" ON public."lease_residents"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "lease_residents_insert" ON public."lease_residents";
CREATE POLICY "lease_residents_insert" ON public."lease_residents"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "lease_residents_update" ON public."lease_residents";
CREATE POLICY "lease_residents_update" ON public."lease_residents"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "lease_residents_delete" ON public."lease_residents";
CREATE POLICY "lease_residents_delete" ON public."lease_residents"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."leases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leases" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "leases_select" ON public."leases";
CREATE POLICY "leases_select" ON public."leases"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "leases_insert" ON public."leases";
CREATE POLICY "leases_insert" ON public."leases"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "leases_update" ON public."leases";
CREATE POLICY "leases_update" ON public."leases"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "leases_delete" ON public."leases";
CREATE POLICY "leases_delete" ON public."leases"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."leasing_leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."leasing_leads" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "leasing_leads_select" ON public."leasing_leads";
CREATE POLICY "leasing_leads_select" ON public."leasing_leads"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "leasing_leads_insert" ON public."leasing_leads";
CREATE POLICY "leasing_leads_insert" ON public."leasing_leads"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "leasing_leads_update" ON public."leasing_leads";
CREATE POLICY "leasing_leads_update" ON public."leasing_leads"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "leasing_leads_delete" ON public."leasing_leads";
CREATE POLICY "leasing_leads_delete" ON public."leasing_leads"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."ledger_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ledger_entries" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ledger_entries_select" ON public."ledger_entries";
CREATE POLICY "ledger_entries_select" ON public."ledger_entries"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "ledger_entries_insert" ON public."ledger_entries";
CREATE POLICY "ledger_entries_insert" ON public."ledger_entries"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "ledger_entries_update" ON public."ledger_entries";
CREATE POLICY "ledger_entries_update" ON public."ledger_entries"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "ledger_entries_delete" ON public."ledger_entries";
CREATE POLICY "ledger_entries_delete" ON public."ledger_entries"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."oauth_states" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."oauth_states" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "oauth_states_select" ON public."oauth_states";
CREATE POLICY "oauth_states_select" ON public."oauth_states"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "oauth_states_insert" ON public."oauth_states";
CREATE POLICY "oauth_states_insert" ON public."oauth_states"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "oauth_states_update" ON public."oauth_states";
CREATE POLICY "oauth_states_update" ON public."oauth_states"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "oauth_states_delete" ON public."oauth_states";
CREATE POLICY "oauth_states_delete" ON public."oauth_states"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."operations_conflicts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."operations_conflicts" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "operations_conflicts_select" ON public."operations_conflicts";
CREATE POLICY "operations_conflicts_select" ON public."operations_conflicts"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "operations_conflicts_insert" ON public."operations_conflicts";
CREATE POLICY "operations_conflicts_insert" ON public."operations_conflicts"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "operations_conflicts_update" ON public."operations_conflicts";
CREATE POLICY "operations_conflicts_update" ON public."operations_conflicts"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "operations_conflicts_delete" ON public."operations_conflicts";
CREATE POLICY "operations_conflicts_delete" ON public."operations_conflicts"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."organization_invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."organization_invitations" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "organization_invitations_select" ON public."organization_invitations";
CREATE POLICY "organization_invitations_select" ON public."organization_invitations"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "organization_invitations_insert" ON public."organization_invitations";
CREATE POLICY "organization_invitations_insert" ON public."organization_invitations"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "organization_invitations_update" ON public."organization_invitations";
CREATE POLICY "organization_invitations_update" ON public."organization_invitations"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "organization_invitations_delete" ON public."organization_invitations";
CREATE POLICY "organization_invitations_delete" ON public."organization_invitations"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."organization_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."organization_members" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "organization_members_select" ON public."organization_members";
CREATE POLICY "organization_members_select" ON public."organization_members"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "organization_members_insert" ON public."organization_members";
CREATE POLICY "organization_members_insert" ON public."organization_members"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "organization_members_update" ON public."organization_members";
CREATE POLICY "organization_members_update" ON public."organization_members"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "organization_members_delete" ON public."organization_members";
CREATE POLICY "organization_members_delete" ON public."organization_members"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."ownership_entities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ownership_entities" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ownership_entities_select" ON public."ownership_entities";
CREATE POLICY "ownership_entities_select" ON public."ownership_entities"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "ownership_entities_insert" ON public."ownership_entities";
CREATE POLICY "ownership_entities_insert" ON public."ownership_entities"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "ownership_entities_update" ON public."ownership_entities";
CREATE POLICY "ownership_entities_update" ON public."ownership_entities"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "ownership_entities_delete" ON public."ownership_entities";
CREATE POLICY "ownership_entities_delete" ON public."ownership_entities"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."planning_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."planning_items" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "planning_items_select" ON public."planning_items";
CREATE POLICY "planning_items_select" ON public."planning_items"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "planning_items_insert" ON public."planning_items";
CREATE POLICY "planning_items_insert" ON public."planning_items"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "planning_items_update" ON public."planning_items";
CREATE POLICY "planning_items_update" ON public."planning_items"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "planning_items_delete" ON public."planning_items";
CREATE POLICY "planning_items_delete" ON public."planning_items"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."planning_projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."planning_projects" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "planning_projects_select" ON public."planning_projects";
CREATE POLICY "planning_projects_select" ON public."planning_projects"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "planning_projects_insert" ON public."planning_projects";
CREATE POLICY "planning_projects_insert" ON public."planning_projects"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "planning_projects_update" ON public."planning_projects";
CREATE POLICY "planning_projects_update" ON public."planning_projects"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "planning_projects_delete" ON public."planning_projects";
CREATE POLICY "planning_projects_delete" ON public."planning_projects"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."portfolio_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."portfolio_snapshots" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "portfolio_snapshots_select" ON public."portfolio_snapshots";
CREATE POLICY "portfolio_snapshots_select" ON public."portfolio_snapshots"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "portfolio_snapshots_insert" ON public."portfolio_snapshots";
CREATE POLICY "portfolio_snapshots_insert" ON public."portfolio_snapshots"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "portfolio_snapshots_update" ON public."portfolio_snapshots";
CREATE POLICY "portfolio_snapshots_update" ON public."portfolio_snapshots"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "portfolio_snapshots_delete" ON public."portfolio_snapshots";
CREATE POLICY "portfolio_snapshots_delete" ON public."portfolio_snapshots"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."portfolios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."portfolios" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "portfolios_select" ON public."portfolios";
CREATE POLICY "portfolios_select" ON public."portfolios"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "portfolios_insert" ON public."portfolios";
CREATE POLICY "portfolios_insert" ON public."portfolios"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "portfolios_update" ON public."portfolios";
CREATE POLICY "portfolios_update" ON public."portfolios"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "portfolios_delete" ON public."portfolios";
CREATE POLICY "portfolios_delete" ON public."portfolios"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."properties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."properties" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "properties_select" ON public."properties";
CREATE POLICY "properties_select" ON public."properties"
  FOR SELECT TO aval_app
  USING (aval_private.can_access_property(organization_id, id));

DROP POLICY IF EXISTS "properties_insert" ON public."properties";
CREATE POLICY "properties_insert" ON public."properties"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "properties_update" ON public."properties";
CREATE POLICY "properties_update" ON public."properties"
  FOR UPDATE TO aval_app
  USING (aval_private.can_manage_property(organization_id, id))
  WITH CHECK (aval_private.can_manage_property(organization_id, id));

DROP POLICY IF EXISTS "properties_delete" ON public."properties";
CREATE POLICY "properties_delete" ON public."properties"
  FOR DELETE TO aval_app
  USING (aval_private.can_manage_property(organization_id, id));

ALTER TABLE public."regions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."regions" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "regions_select" ON public."regions";
CREATE POLICY "regions_select" ON public."regions"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "regions_insert" ON public."regions";
CREATE POLICY "regions_insert" ON public."regions"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "regions_update" ON public."regions";
CREATE POLICY "regions_update" ON public."regions"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "regions_delete" ON public."regions";
CREATE POLICY "regions_delete" ON public."regions"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."residents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."residents" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "residents_select" ON public."residents";
CREATE POLICY "residents_select" ON public."residents"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "residents_insert" ON public."residents";
CREATE POLICY "residents_insert" ON public."residents"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "residents_update" ON public."residents";
CREATE POLICY "residents_update" ON public."residents"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "residents_delete" ON public."residents";
CREATE POLICY "residents_delete" ON public."residents"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."sso_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sso_connections" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sso_connections_select" ON public."sso_connections";
CREATE POLICY "sso_connections_select" ON public."sso_connections"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "sso_connections_insert" ON public."sso_connections";
CREATE POLICY "sso_connections_insert" ON public."sso_connections"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "sso_connections_update" ON public."sso_connections";
CREATE POLICY "sso_connections_update" ON public."sso_connections"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

DROP POLICY IF EXISTS "sso_connections_delete" ON public."sso_connections";
CREATE POLICY "sso_connections_delete" ON public."sso_connections"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin']));

ALTER TABLE public."subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."subscriptions" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subscriptions_select" ON public."subscriptions";
CREATE POLICY "subscriptions_select" ON public."subscriptions"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "subscriptions_insert" ON public."subscriptions";
CREATE POLICY "subscriptions_insert" ON public."subscriptions"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "subscriptions_update" ON public."subscriptions";
CREATE POLICY "subscriptions_update" ON public."subscriptions"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "subscriptions_delete" ON public."subscriptions";
CREATE POLICY "subscriptions_delete" ON public."subscriptions"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."sync_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sync_runs" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sync_runs_select" ON public."sync_runs";
CREATE POLICY "sync_runs_select" ON public."sync_runs"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "sync_runs_insert" ON public."sync_runs";
CREATE POLICY "sync_runs_insert" ON public."sync_runs"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "sync_runs_update" ON public."sync_runs";
CREATE POLICY "sync_runs_update" ON public."sync_runs"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "sync_runs_delete" ON public."sync_runs";
CREATE POLICY "sync_runs_delete" ON public."sync_runs"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."token_top_ups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."token_top_ups" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "token_top_ups_select" ON public."token_top_ups";
CREATE POLICY "token_top_ups_select" ON public."token_top_ups"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "token_top_ups_insert" ON public."token_top_ups";
CREATE POLICY "token_top_ups_insert" ON public."token_top_ups"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "token_top_ups_update" ON public."token_top_ups";
CREATE POLICY "token_top_ups_update" ON public."token_top_ups"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "token_top_ups_delete" ON public."token_top_ups";
CREATE POLICY "token_top_ups_delete" ON public."token_top_ups"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."units" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."units" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "units_select" ON public."units";
CREATE POLICY "units_select" ON public."units"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "units_insert" ON public."units";
CREATE POLICY "units_insert" ON public."units"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "units_update" ON public."units";
CREATE POLICY "units_update" ON public."units"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "units_delete" ON public."units";
CREATE POLICY "units_delete" ON public."units"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."user_onboarding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_onboarding" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_onboarding_select" ON public."user_onboarding";
CREATE POLICY "user_onboarding_select" ON public."user_onboarding"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "user_onboarding_insert" ON public."user_onboarding";
CREATE POLICY "user_onboarding_insert" ON public."user_onboarding"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "user_onboarding_update" ON public."user_onboarding";
CREATE POLICY "user_onboarding_update" ON public."user_onboarding"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "user_onboarding_delete" ON public."user_onboarding";
CREATE POLICY "user_onboarding_delete" ON public."user_onboarding"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."utility_bills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."utility_bills" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "utility_bills_select" ON public."utility_bills";
CREATE POLICY "utility_bills_select" ON public."utility_bills"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "utility_bills_insert" ON public."utility_bills";
CREATE POLICY "utility_bills_insert" ON public."utility_bills"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "utility_bills_update" ON public."utility_bills";
CREATE POLICY "utility_bills_update" ON public."utility_bills"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "utility_bills_delete" ON public."utility_bills";
CREATE POLICY "utility_bills_delete" ON public."utility_bills"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."utility_meters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."utility_meters" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "utility_meters_select" ON public."utility_meters";
CREATE POLICY "utility_meters_select" ON public."utility_meters"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "utility_meters_insert" ON public."utility_meters";
CREATE POLICY "utility_meters_insert" ON public."utility_meters"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "utility_meters_update" ON public."utility_meters";
CREATE POLICY "utility_meters_update" ON public."utility_meters"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "utility_meters_delete" ON public."utility_meters";
CREATE POLICY "utility_meters_delete" ON public."utility_meters"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."vendors" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vendors_select" ON public."vendors";
CREATE POLICY "vendors_select" ON public."vendors"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "vendors_insert" ON public."vendors";
CREATE POLICY "vendors_insert" ON public."vendors"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "vendors_update" ON public."vendors";
CREATE POLICY "vendors_update" ON public."vendors"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "vendors_delete" ON public."vendors";
CREATE POLICY "vendors_delete" ON public."vendors"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public."work_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."work_orders" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "work_orders_select" ON public."work_orders";
CREATE POLICY "work_orders_select" ON public."work_orders"
  FOR SELECT TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_access(organization_id)) OR aval_private.can_access_property(organization_id, property_id));

DROP POLICY IF EXISTS "work_orders_insert" ON public."work_orders";
CREATE POLICY "work_orders_insert" ON public."work_orders"
  FOR INSERT TO aval_app
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "work_orders_update" ON public."work_orders";
CREATE POLICY "work_orders_update" ON public."work_orders"
  FOR UPDATE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id))
  WITH CHECK ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

DROP POLICY IF EXISTS "work_orders_delete" ON public."work_orders";
CREATE POLICY "work_orders_delete" ON public."work_orders"
  FOR DELETE TO aval_app
  USING ((property_id IS NULL AND aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator'])) OR aval_private.can_manage_property(organization_id, property_id));

ALTER TABLE public."workspace_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."workspace_usage" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workspace_usage_select" ON public."workspace_usage";
CREATE POLICY "workspace_usage_select" ON public."workspace_usage"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(organization_id));

DROP POLICY IF EXISTS "workspace_usage_insert" ON public."workspace_usage";
CREATE POLICY "workspace_usage_insert" ON public."workspace_usage"
  FOR INSERT TO aval_app
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "workspace_usage_update" ON public."workspace_usage";
CREATE POLICY "workspace_usage_update" ON public."workspace_usage"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']))
  WITH CHECK (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

DROP POLICY IF EXISTS "workspace_usage_delete" ON public."workspace_usage";
CREATE POLICY "workspace_usage_delete" ON public."workspace_usage"
  FOR DELETE TO aval_app
  USING (aval_private.has_org_role(organization_id, ARRAY['org_admin','regional_manager','property_manager','operator']));

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "organizations_select" ON public."organizations";
CREATE POLICY "organizations_select" ON public."organizations"
  FOR SELECT TO aval_app
  USING (aval_private.has_org_access(id));

DROP POLICY IF EXISTS "organizations_update" ON public."organizations";
CREATE POLICY "organizations_update" ON public."organizations"
  FOR UPDATE TO aval_app
  USING (aval_private.has_org_role(id, ARRAY['org_admin']))
  WITH CHECK (aval_private.has_org_role(id, ARRAY['org_admin']));

ALTER TABLE public.principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.principals FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "principals_select" ON public."principals";
CREATE POLICY "principals_select" ON public."principals"
  FOR SELECT TO aval_app
  USING (id = aval_private.current_principal_id());

ALTER TABLE public.identity_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.identity_links FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "identity_links_select" ON public."identity_links";
CREATE POLICY "identity_links_select" ON public."identity_links"
  FOR SELECT TO aval_app
  USING (principal_id = aval_private.current_principal_id());

CREATE OR REPLACE FUNCTION aval_private.protect_final_org_admin() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE target_org text := COALESCE(OLD.organization_id, NEW.organization_id);
BEGIN
  IF OLD.role = 'org_admin' AND OLD.organization_scope AND OLD.revoked_at IS NULL
     AND (TG_OP = 'DELETE' OR NEW.role <> 'org_admin' OR NOT NEW.organization_scope OR NEW.revoked_at IS NOT NULL) THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.access_grants candidate
      WHERE candidate.organization_id = target_org
        AND candidate.id <> OLD.id
        AND candidate.role = 'org_admin'
        AND candidate.organization_scope
        AND candidate.revoked_at IS NULL
        AND (candidate.expires_at IS NULL OR candidate.expires_at > statement_timestamp())
    ) THEN RAISE EXCEPTION 'cannot remove the final organization administrator' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$;

DROP TRIGGER IF EXISTS access_grants_final_admin_guard ON public.access_grants;
CREATE CONSTRAINT TRIGGER access_grants_final_admin_guard
AFTER UPDATE OR DELETE ON public.access_grants DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION aval_private.protect_final_org_admin();

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA aval_private FROM PUBLIC;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA aval_private TO aval_app;
